In [1]:
import  pandas as pd
import matplotlib.pyplot as plt
from IPython.display import Image

In [2]:
def get_counts(anything):
    counts = {}
    for a in anything:
        if  a in counts:
            counts[a] = counts[a] + 1
        else:
            counts[a] = 1
    return counts

In [4]:
path_3 =  'F:/Stage/data/AFC/counts/counts_3'
data = pd.read_csv(path_3, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
data

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
0,2,05555646578518204505,14/03/2017,08:16:32,GARE DE LYON,1,801,0030050091300,214,57,3,810,801,ND
1,4,58112168677996473715,14/03/2017,07:03:09,PETIT-VAUX,2,2,393652,1651401,1,1,800,803,ND
2,13,58733986662879801363,14/03/2017,18:15:38,BIR-HAKEIM (GRENELLE),3,1,0030030100400,103,31,3,100,110,ND
3,22,14518383320337389570,14/03/2017,16:46:44,TRAPPES,2,2,393835,15601102,1,1,800,852,ND
4,26,78252539046252801159,14/03/2017,17:34:11,HAUSSMANN-SAINT-LAZARE,2,2,281899,26500003,1,1,800,805,ND
5,29,43724842314677126247,14/03/2017,06:05:32,AUBERVILLIERS-PANTIN (QUATRE CHEMINS),3,1,0030030030500,105,31,3,100,110,ND
6,38,35582761024116677984,14/03/2017,07:58:15,FONTENAY-AUX-ROSES,1,802,0030050280402,333,51,1,810,802,ND
7,50,61023525515334729319,14/03/2017,16:12:26,MARCEL SEMBAT-METRO,3,1,0030010126029,277,11,2,100,100,126
8,65,86519358410939464720,14/03/2017,19:49:36,CLEMENCEAU,3,1,0030010272020,8237,11,2,100,100,272
9,73,83190830723169792819,14/03/2017,20:13:57,BONNE NOUVELLE,3,1,0030030110800,103,31,3,100,110,ND
10,79,32799638832095310366,14/03/2017,08:13:23,CHAMP DE MARS-TOUR EIFFEL,2,2,393058,11640101,1,1,800,803,ND
11,84,50508698981533083564,14/03/2017,13:44:05,LES BACONNETS,1,802,0030050180503,147,52,1,810,802,ND
12,86,78478524383148766348,14/03/2017,14:49:10,GENERAL DE GAULLE - STALINGRAD,3,1,0030010317030,5130,11,2,100,100,317
13,90,05555646578518204505,14/03/2017,08:16:09,GARE DE LYON,1,801,0030050091300,239,51,1,810,801,ND
14,92,58112168677996473715,14/03/2017,18:43:19,AUSTERLITZ,2,2,547026,34410101,1,1,800,803,ND
15,100,04067105307557541933,14/03/2017,18:09:49,HAVRE-CAUMARTIN,3,1,0030030060700,106,31,3,100,110,ND
16,101,58733986662879801363,14/03/2017,22:30:17,SAINT-PLACIDE,3,1,0030030041200,161,31,3,100,110,ND
17,126,35582761024116677984,14/03/2017,17:17:40,FONTENAY-AUX-ROSES,1,802,0030050280402,243,52,1,810,802,ND
18,172,50508698981533083564,14/03/2017,17:19:12,LES BACONNETS,1,802,0030050180503,133,51,1,810,802,ND
19,175,94279463664649774754,14/03/2017,07:47:28,BRUNOY,2,2,682120,3431003,1,1,800,804,ND
20,178,05555646578518204505,14/03/2017,17:22:06,TRINITE-D'ESTIENNE D'ORVES,3,1,0030030310800,104,31,3,100,110,ND
21,179,81436157518174117240,14/03/2017,18:58:19,STADE DE FRANCE-SAINT-DENIS,2,2,164780,16500403,1,1,800,804,ND
22,199,37535286183140111215,14/03/2017,17:11:38,LES COURTILLES,3,1,0030010921065,8786,41,4,100,112,11
23,242,01310300870072006700,14/03/2017,19:22:24,PLACE CHARRAS,3,1,0030010176005,777,11,2,100,100,176
24,254,14738355525455091886,14/03/2017,17:02:12,SEVRAN-BEAUDOTTES,1,802,271445,14700901,1,1,810,802,ND
25,257,24351878581399459805,14/03/2017,12:23:25,OLYMPIADES,3,1,0030030150600,101,31,3,100,110,ND
26,260,50508698981533083564,14/03/2017,12:46:53,VITRY-SUR-SEINE,2,2,545293,22410402,1,1,800,803,ND
27,263,94279463664649774754,14/03/2017,08:21:13,GARE DE LYON,1,801,0030050091300,242,57,3,810,801,ND
28,267,16198507190863620984,14/03/2017,17:20:00,SAINT-PHILIPPE-DU-ROULE,3,1,0030030180500,101,31,3,100,110,ND
29,278,55831230359662085980,14/03/2017,07:38:50,RUE DE JOINVILLE,3,1,0030010124013,11804,11,2,100,100,124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392855,13099095,83202628273035109587,14/03/2017,10:53:00,Les Sarments,130,195,288,48003,11,2,30,195,3
1392856,13099110,63954009552760280114,14/03/2017,09:31:30,BOIS-LE-ROI,2,002,682203,1441601,1,1,800,851,ND
1392857,13099112,63954009552760280114,14/03/2017,10:21:34,GARE DE LYON,3,001,0030030090800,121,31,3,100,110,ND
1392858,13099144,17904932375790758250,14/03/2017,07:48:42,LAPLACE,1,802,0030050180202,170,51,1,810,802,ND
1392859,13099146,17904932375790758250,14/03/2017,18:31:22,GIF-SUR-YVETTE,1,802,0030050181003,432,51,1,810,802,ND
1392860,13099148,17904932375790758250,14/03/2017,00:57:29,LAPLACE,1,802,0030050180202,175,52,1,810,802,ND
1392861,13099188,45993039426701202251,14/03/2017,22:27:17,MASSY-PALAISEAU,1,802,0030050180602,104,51,1,810,802,ND
1392862,13099191,45622845620778886487,14/03/2017,19:39:09,VINCENNES,1,801,0030050160201,109,51,1,810,801,ND
1392863,13099192,45622845620778886487,14/03/2017,19:45:17,VAL-DE-FONTENAY,1,801,0030050260501,152,52,1,810,801,ND
1392864,13099229,92082075111097025019,14/03/2017,17:20:22,PRESIDENT ROBERT SCHUMAN,3,001,0030010189008,372,11,2,100,100,189
1392865,13099230,92082075111097025019,14/03/2017,17:26:14,CORENTIN-CELTON,3,001,0030030280200,102,31,3,100,110,ND
1392866,13099233,45438195472914678351,14/03/2017,21:41:21,LA DEFENSE-GRANDE ARCHE,1,801,0030050170401,304,52,1,810,801,ND
1392867,13099234,45438195472914678351,14/03/2017,07:42:57,LA DEFENSE-GRANDE ARCHE,1,801,0030050170401,103,31,3,810,801,ND
1392868,13099277,80038784424562865230,14/03/2017,17:29:58,GARE SAINT LAZARE,3,001,0030010095066,13715,11,2,100,100,95
1392869,13099291,18721456883410287200,14/03/2017,06:24:01,SAINT-CYR,2,002,393223,11601001,1,1,800,852,ND
1392870,13099292,17607762558059928364,14/03/2017,18:44:40,ROME,3,001,0030030311200,102,31,3,100,110,ND
1392871,13099318,73685933586312357799,14/03/2017,16:25:36,MUSEE DE SEVRES,3,001,0030010171002,11491,11,2,100,100,171
1392872,13099335,92586163951459637641,14/03/2017,07:35:14,PONT DE CHARENTON,3,001,0030010024037,11873,11,2,100,100,24
1392873,13099336,92586163951459637641,14/03/2017,07:41:21,CHARENTON-ECOLES,3,001,0030030251300,101,31,3,100,110,ND
1392874,13099357,23909116738615351722,14/03/2017,18:51:30,MAIRIE DES LILAS - METRO,3,001,0030010105003,6984,11,2,100,100,105
1392875,13099373,06956755301916622050,14/03/2017,11:38:34,SAINT-DENIS,2,002,271015,6500505,1,1,800,853,ND
1392876,13099374,06956755301916622050,14/03/2017,23:03:33,SAINT-DENIS,2,002,271015,13500505,2,1,800,853,ND
1392877,13099388,95220845022684976437,14/03/2017,19:20:26,MICHEL-ANGE - AUTEUIL,3,001,0030010062006,5323,11,2,100,100,62
1392878,13099427,91275327765951983217,14/03/2017,08:10:34,ARGENTINE,3,001,0030030181100,102,31,3,100,110,ND
1392879,13099429,20738421309354187838,14/03/2017,08:25:56,ROBERT WAGNER,3,001,0030010016041,12033,41,4,100,112,16
1392880,13099430,20738421309354187838,14/03/2017,08:54:51,JAVEL,2,002,393066,18640201,2,1,800,803,ND
1392881,13099435,33371669723630670778,14/03/2017,09:00:29,SAINT-LAZARE,3,001,0030030060900,207,31,3,100,110,ND
1392882,13099440,00046590185045852222,14/03/2017,17:48:38,CHATILLON-MONTROUGE,3,001,0030010016001,6753,41,4,100,112,16
1392883,13099441,18502851121848883987,14/03/2017,18:43:07,EDGAR QUINET,3,001,0030030040600,101,31,3,100,110,ND
1392884,13099451,63770673800892266274,14/03/2017,12:14:20,PLACE DES FETES,3,001,0030010060042,993,11,2,100,100,60

In [6]:
test_1 = get_counts(data['COD_NATR_VALD'])
test_1

{57: 18362,
 1: 161012,
 31: 414939,
 51: 54814,
 11: 308572,
 52: 40330,
 41: 40747,
 2: 57577,
 4: 9079,
 17: 6543,
 56: 10118,
 3: 6537,
 22: 32,
 43: 2061,
 42: 18,
 '011': 18169,
 '031': 27082,
 '01 ': 11028,
 '052': 3703,
 '051': 5025,
 '11 ': 7042,
 '041': 3297,
 '043': 62,
 '02 ': 4273,
 '056': 260,
 '057': 444,
 '03 ': 198,
 '04 ': 255,
 '17 ': 569,
 'ND ': 6,
 '11': 51451,
 '31': 67703,
 '1': 26068,
 '2': 8799,
 '52': 5917,
 '51': 7924,
 '41': 7146,
 '57': 1075,
 '43': 525,
 '4': 1130,
 '3': 966,
 '56': 773,
 '17': 1241,
 '42': 9,
 '22 ': 2,
 '22': 2}

In [7]:
data[data['NUMR_CART'] == '43724842314677126247']

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
5,29,43724842314677126247,14/03/2017,06:05:32,AUBERVILLIERS-PANTIN (QUATRE CHEMINS),3,1,0030030030500,105,31,3,100,110,ND
952870,8917597,43724842314677126247,14/03/2017,15:06:04,GARE DE L'EST,3,001,0030030210900,308,31,3,100,110,ND
952878,8917685,43724842314677126247,14/03/2017,15:43:40,Inconnu,3,001,*100,5520,11,2,100,100,170

In [9]:
data[data['NUMR_CART'] == '14518383320337389570']

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
3,22,14518383320337389570,14/03/2017,16:46:44,TRAPPES,2,2,393835,15601102,1,1,800,852,ND
487918,4779566,14518383320337389570,14/03/2017,16:38:00,St-Francois,136,230,165,5344,11,2,230,410,414
487928,4779654,14518383320337389570,14/03/2017,12:59:37,LA VERRIERE,2,002,393256,12601201,1,1,800,852,ND