In [1]:
import pandas as pd

In [2]:
def get_counts(anything):
    counts ={}
    for a in anything:
        if a in counts:
            counts[a] = counts[a] + 1
        else:
            counts[a] = 1
    return counts

In [3]:
pd.options.display.max_rows = 50
pd.options.display.max_columns = 21

In [4]:
path_arret = "F:/Stage/data/AFC/DM arret.txt"

In [5]:
arrets = pd.read_csv(path_arret, header=0, delimiter="\t", encoding="latin-1")
arrets

,COD_TLB_RES,COD_TLB_TRNS,COD_TLB_ARRT_STTN,COD_STF_RES,COD_STF_TRNS,COD_STF_ARRT_STTN,ZONS_ARRT,COD_ZON_PHSQ_MIN,DAT_DEBT_VALD_ZON_PHSQ_MIN,COD_INS_COMM,COD_ARRT_COMM,COD_ZON_PHSQ_MAX,DAT_DEBT_VALD_ZON_PHSQ_MAX,LIBL_COUR_ARRT_STTN,LIBL_LONG_ARRT_STTN,POL_PDU,COOR_X_PHSQ,COOR_Y_PHSQ,CORR_DONN_STF,MOD_BUS,MOD_RER
0,123,168,1133,913,68,1133,6,6,01/07/2011,91081,1265,6,01/07/2011,Le Rotoir,Le Rotoir,0,"581349,393411518","88308,4118717562",O,1,0
1,208,108,3244,208,208,3244,8,8,01/07/2011,77409,1327677,8,01/07/2011,ST PIERRE MO,St Pierre Moulin,0,"648173,847524997","77796,3503673696",O,1,0
2,193,100,35808,193,293,35808,4,4,01/01/2006,-1,-1,4,01/01/2006,35808,35808,?,"616988,443650252","140716,811558468",N,1,0
3,193,100,16161,193,293,16161,4,4,01/01/2006,93047,1490007,4,01/01/2006,VICTOR HUGO,Victor Hugo,0,"616468,683052773","133535,437651189",O,1,0
4,220,106,8320,220,6,8320,4,4,01/01/2006,91064,-1,4,01/01/2006,Burospace,Burospace,0,"591110,573297878","118548,266468109",O,1,0
5,001,3,0030010068064,100,100,0030010068064,2,2,01/01/2006,92049,-1,2,01/01/2006,PLACE DES ETAT,PLACE DES ETATS-UNIS,?,"598501,833436911","124118,998066932",N,1,0
6,001,3,0030010763006,987,100,0030010763006,1,1,01/01/2006,75114,-1,1,01/01/2006,PLAISANCE,PLAISANCE,0,"598177,037106543","125811,050509275",O,1,0
7,39,139,33,39,39,33,5,5,01/01/2006,91272,3571,5,01/01/2006,COL. J. ADAM,Coll√®ge Juliette Adam,0,"584438,155579861","111235,437093641",O,1,0
8,55,155,604,55,55,604,-1,-1,01/01/2000,91587,-1,-1,01/01/2000,BUHOTERIE,BUHOTERIE,?,-1,-1,N,1,0
9,57,157,524,57,57,524,6,6,01/07/2011,78354,1368030,6,01/07/2011,Magnanville Ly,Lyc√©e L√©opold Sedar Senghor,0,"552188,584037208","140945,14538049",O,1,0
10,45,145,45479,45,45,45479,5,5,01/01/2006,91114,1364118,5,01/01/2006,JEAN XXIII,JEAN XXIII,0,"612118,393208712","111614,906683661",O,1,0
11,001,3,0030010166009,100,100,0030010166009,3,3,01/01/2006,93039,17716,3,01/01/2006,BOULEVARD MARC,BOULEVARD MARCEL PAUL,0,"599309,442786037","135495,181686257",O,1,0
12,99,121,1,987,21,1,-1,-1,01/01/2000,-1,-1,-1,01/01/2000,Gare de Lyon,Gare de Lyon,?,-1,-1,N,1,0
13,126,117,360,366,97,360,6,6,01/07/2011,77528,132747,6,01/07/2011,,Le Plateau,0,"624182,430686111","97086,469752711",O,1,0
14,234,175,1471,327,213,1471,3,3,01/01/2006,92063,2292186,3,01/01/2006,PASSY BUZENV,PASSY BUZENVAL,0,"588609,732397951","128802,78873261",O,1,0
15,95,203,50828,295,116,50828,5,5,01/01/2006,95250,-1,5,01/01/2006,Fose-Beaumon,Fose-Beaumon,?,"613013,673612522","155795,254537152",N,1,0
16,213,175,253,213,213,253,3,3,01/01/2006,92064,2292236,3,01/01/2006,ST CLOUD GAR,ST CLOUD GARE SNCF,0,"591251,061141332","127119,573982953",O,1,0
17,193,100,28242,193,293,28242,4,4,01/01/2006,93062,1490012,4,01/01/2006,LE PLATEAU,Le Plateau,0,"613871,377821073","132881,550569458",O,1,0
18,001,3,0030010098019,100,100,0030010098019,1,1,01/01/2006,75120,-1,1,01/01/2006,PAGANINI,PAGANINI,0,"605466,808457059","127837,981757609",O,1,0
19,001,3,0030010184027,100,100,0030010184027,3,3,01/01/2006,94034,742048,3,01/01/2006,LA PEUPLERAIE,LA PEUPLERAIE,0,"598440,788532407","117380,576342075",O,1,0
20,240,140,58801,240,40,58801,5,5,01/01/2006,77373,-1,5,01/01/2006,CLINIQUE LA,CLINIQUE LA,?,"619750,300108413","122219,48992418",N,1,0
21,218,189,268,350,350,268,6,6,01/07/2011,78291,1611654,6,01/07/2011,,Convois,0,"555681,118454606","140678,120382331",O,1,0
22,25,124,1114,309,24,1114,5,5,01/01/2006,91174,1431031,5,01/01/2006,Parc Robinso,Angoul√™me,0,"609280,511833548","99960,5659029053",O,1,0
23,8,164,1003,608,64,1003,-1,-1,01/01/2000,77329,-1,-1,01/01/2000,LE PRIEURE,LE PRIEURE,?,-1,-1,N,1,0
24,147,203,50755,277,116,50755,5,5,01/01/2006,77514,2245843,5,01/01/2006,Vipa-Laroche,Laroche,0,"620137,63835545","138485,748698624",O,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79305,14,141,494,14,147,494,5,5,01/01/2006,93073,-1,5,01/01/2006,HUB POSTAL,HUB POSTAL,?,"615307,27904961","143399,756129403",N,1,0
79306,62,162,244,62,62,244,6,6,01/07/2011,77280,1315935,6,01/07/2011,CROIX BLANCH,CROIX BLANCHE,0,"621793,841791459","93598,2515272603",O,1,0
79307,10,110,59511,10,10,59511,5,5,01/01/2006,91549,1832539,5,01/01/2006,Claire Joie,Claire Joie,0,"597587,003299347","105321,145232818",O,1,0
79308,13,113,10519,13,13,10519,5,5,01/01/2006,78168,-1,5,01/01/2006,Les Fontaine,Les Fontaine,?,"569899,043220157","116608,337214292",N,1,0
79309,140,140,192,40,40,192,5,5,01/01/2006,77296,-1,5,01/01/2006,Gare Lieusai,Gare Lieusai,?,"617261,107264193","103122,128869076",N,1,0
79310,193,100,36868,193,293,36868,4,4,01/01/2006,-1,-1,4,01/01/2006,36868,36868,?,"616988,443650252","140716,811558468",N,1,0
79311,136,117,349,136,97,349,6,6,01/07/2011,77192,-1,6,01/07/2011,FONTENAY,FONTENAY-TRESIGNY BOULEVARD HARDY,0,"638612,996708815","112138,675728584",O,1,0
79312,001,3,0030010753007,987,100,0030010753007,3,3,01/01/2006,92050,-1,3,01/01/2006,SADI-CARNOT-JO,SADI-CARNOT-JOLIOT-CURIE,?,"590275,987242363","132090,673224313",N,1,0
79313,8,184,442,608,84,442,8,8,01/07/2011,77431,-1,8,01/07/2011,Maison de re,Maison de re,?,"626569,439776681","62290,7450807658",N,1,0
79314,230,127,10,410,27,10,3,3,01/01/2006,92023,-1,3,01/01/2006,Mail Plaine,Mail Plaine,?,"593442,461586861","120341,197662486",N,1,0
79315,87,165,95,487,65,95,5,5,01/01/2006,77250,2285263,5,01/01/2006,PARISUD ESPA,ZAE ESPAGNE,0,"615523,616462596","104714,271964754",O,1,0
79316,001,3,0030010152045,100,100,0030010152045,3,3,01/01/2006,93027,-1,3,01/01/2006,8 MAI 1945-MET,8 MAI 1945-METRO,0,"605620,381041192","135865,060357149",O,1,0
79317,97,117,128,97,97,128,8,8,01/07/2011,77030,6878,8,01/07/2011,,Place,0,"671992,453004472","128951,604888438",O,1,0
79318,57,157,289,57,57,289,6,6,01/07/2011,78314,1455657,6,01/07/2011,,Charvets,0,"560627,680141118","143791,418078571",O,1,0
79319,8,164,50,608,64,50,7,7,01/07/2011,77048,2285533,7,01/07/2011,SQUARE THIBA,SQUARE THIBAULT,0,"628074,330398038","71751,8101392938",O,1,0
79320,24,124,1152,24,24,1152,5,5,01/01/2006,91435,278510,5,01/01/2006,Cie des Eaux,Compagnie des Eaux,0,"611373,961178061","97170,7462180511",O,1,0
79321,1,126,3129,501,501,3129,-1,-1,01/01/2000,95199,-1,-1,01/01/2000,TOURNESOLS,TOURNESOLS,?,-1,-1,N,1,0
79322,193,100,37371,193,293,37371,4,4,01/01/2006,-1,-1,4,01/01/2006,37371,37371,?,"616988,443650252","140716,811558468",N,1,0
79323,149,120,31500,149,20,31500,3,3,01/01/2006,92071,923868,3,01/01/2006,Les Musicien,Les Musiciens,0,"597788,168453824","120400,024486425",O,1,0
79324,250,186,587,320,86,587,-1,-1,01/01/2000,-1,-1,-1,01/01/2000,LES ESSARTS,LES ESSARTS,?,-1,-1,N,1,0
79325,193,100,37236,193,293,37236,4,4,01/01/2006,-1,-1,4,01/01/2006,37236,37236,?,"616988,443650252","140716,811558468",N,1,0
79326,149,120,30421,149,20,30421,3,3,01/01/2006,92019,923760,3,01/01/2006,Chateaubrian,Chateaubriand,0,"595033,585493287","119372,637125278",O,1,0
79327,230,139,92,410,39,92,-1,-1,01/01/2000,78208,-1,-1,01/01/2000,M. CERDAN,M. CERDAN,?,-1,-1,N,1,0
79328,193,100,37645,193,293,37645,4,4,01/01/2006,-1,-1,4,01/01/2006,37645,37645,?,"616988,443650252","140716,811558468",N,1,0
79329,193,100,25380,193,293,25380,4,4,01/01/2006,93005,-1,4,01/01/2006,POISSONS,POISSONS,0,"612284,727686037","139797,917178056",O,1,0

In [24]:
len(get_counts(arrets['COD_STF_TRNS']))

80

In [34]:
arrets = arrets[arrets.ZONS_ARRT != 'ND ']
arrets = arrets[arrets.COOR_X_PHSQ != '-1']
arrets['COD_TLB_ARRT_STTN'] = arrets['COD_TLB_ARRT_STTN'].astype('int64')

ValueError: invalid literal for int() with base 10: '00E00E0290501'

In [8]:
arrets

,COD_TLB_RES,COD_TLB_TRNS,COD_TLB_ARRT_STTN,COD_STF_RES,COD_STF_TRNS,COD_STF_ARRT_STTN,ZONS_ARRT,COD_ZON_PHSQ_MIN,DAT_DEBT_VALD_ZON_PHSQ_MIN,COD_INS_COMM,COD_ARRT_COMM,COD_ZON_PHSQ_MAX,DAT_DEBT_VALD_ZON_PHSQ_MAX,LIBL_COUR_ARRT_STTN,LIBL_LONG_ARRT_STTN,POL_PDU,COOR_X_PHSQ,COOR_Y_PHSQ,CORR_DONN_STF,MOD_BUS,MOD_RER
0,123,168,1133,913,68,1133,6,6,01/07/2011,91081,1265,6,01/07/2011,Le Rotoir,Le Rotoir,0,"581349,393411518","88308,4118717562",O,1,0
1,208,108,3244,208,208,3244,8,8,01/07/2011,77409,1327677,8,01/07/2011,ST PIERRE MO,St Pierre Moulin,0,"648173,847524997","77796,3503673696",O,1,0
2,193,100,35808,193,293,35808,4,4,01/01/2006,-1,-1,4,01/01/2006,35808,35808,?,"616988,443650252","140716,811558468",N,1,0
3,193,100,16161,193,293,16161,4,4,01/01/2006,93047,1490007,4,01/01/2006,VICTOR HUGO,Victor Hugo,0,"616468,683052773","133535,437651189",O,1,0
4,220,106,8320,220,6,8320,4,4,01/01/2006,91064,-1,4,01/01/2006,Burospace,Burospace,0,"591110,573297878","118548,266468109",O,1,0
5,001,3,0030010068064,100,100,0030010068064,2,2,01/01/2006,92049,-1,2,01/01/2006,PLACE DES ETAT,PLACE DES ETATS-UNIS,?,"598501,833436911","124118,998066932",N,1,0
6,001,3,0030010763006,987,100,0030010763006,1,1,01/01/2006,75114,-1,1,01/01/2006,PLAISANCE,PLAISANCE,0,"598177,037106543","125811,050509275",O,1,0
7,39,139,33,39,39,33,5,5,01/01/2006,91272,3571,5,01/01/2006,COL. J. ADAM,Coll√®ge Juliette Adam,0,"584438,155579861","111235,437093641",O,1,0
9,57,157,524,57,57,524,6,6,01/07/2011,78354,1368030,6,01/07/2011,Magnanville Ly,Lyc√©e L√©opold Sedar Senghor,0,"552188,584037208","140945,14538049",O,1,0
10,45,145,45479,45,45,45479,5,5,01/01/2006,91114,1364118,5,01/01/2006,JEAN XXIII,JEAN XXIII,0,"612118,393208712","111614,906683661",O,1,0
11,001,3,0030010166009,100,100,0030010166009,3,3,01/01/2006,93039,17716,3,01/01/2006,BOULEVARD MARC,BOULEVARD MARCEL PAUL,0,"599309,442786037","135495,181686257",O,1,0
13,126,117,360,366,97,360,6,6,01/07/2011,77528,132747,6,01/07/2011,,Le Plateau,0,"624182,430686111","97086,469752711",O,1,0
14,234,175,1471,327,213,1471,3,3,01/01/2006,92063,2292186,3,01/01/2006,PASSY BUZENV,PASSY BUZENVAL,0,"588609,732397951","128802,78873261",O,1,0
15,95,203,50828,295,116,50828,5,5,01/01/2006,95250,-1,5,01/01/2006,Fose-Beaumon,Fose-Beaumon,?,"613013,673612522","155795,254537152",N,1,0
16,213,175,253,213,213,253,3,3,01/01/2006,92064,2292236,3,01/01/2006,ST CLOUD GAR,ST CLOUD GARE SNCF,0,"591251,061141332","127119,573982953",O,1,0
17,193,100,28242,193,293,28242,4,4,01/01/2006,93062,1490012,4,01/01/2006,LE PLATEAU,Le Plateau,0,"613871,377821073","132881,550569458",O,1,0
18,001,3,0030010098019,100,100,0030010098019,1,1,01/01/2006,75120,-1,1,01/01/2006,PAGANINI,PAGANINI,0,"605466,808457059","127837,981757609",O,1,0
19,001,3,0030010184027,100,100,0030010184027,3,3,01/01/2006,94034,742048,3,01/01/2006,LA PEUPLERAIE,LA PEUPLERAIE,0,"598440,788532407","117380,576342075",O,1,0
20,240,140,58801,240,40,58801,5,5,01/01/2006,77373,-1,5,01/01/2006,CLINIQUE LA,CLINIQUE LA,?,"619750,300108413","122219,48992418",N,1,0
21,218,189,268,350,350,268,6,6,01/07/2011,78291,1611654,6,01/07/2011,,Convois,0,"555681,118454606","140678,120382331",O,1,0
22,25,124,1114,309,24,1114,5,5,01/01/2006,91174,1431031,5,01/01/2006,Parc Robinso,Angoul√™me,0,"609280,511833548","99960,5659029053",O,1,0
24,147,203,50755,277,116,50755,5,5,01/01/2006,77514,2245843,5,01/01/2006,Vipa-Laroche,Laroche,0,"620137,63835545","138485,748698624",O,1,0
25,001,3,0030010743038,987,100,0030010743038,4,4,01/01/2006,95268,2013968,4,01/01/2006,GARGES-SARCELL,GARGES - SARCELLES RER,0,"604033,222295013","141833,026549742",O,1,0
26,70,170,44,70,70,44,5,5,01/01/2006,91182,1708372,5,01/01/2006,G. BRASSENS,LP BRASSENS,0,"606364,470838886","102851,278577561",O,1,0
27,193,203,1344,193,116,1344,5,5,01/01/2006,93073,-1,5,01/01/2006,Trf-Ruedesvi,Trf-Ruedesvi,?,"615503,960997384","144949,684449821",N,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79302,227,118,18029,227,18,18029,5,5,01/01/2006,91103,-1,5,01/01/2006,LES ARDRETS,LES ARDRETS,?,"597943,777447172","100235,157401138",N,1,0
79303,001,3,0030010208092,100,100,0030010208092,4,4,01/01/2006,94017,187552,4,01/01/2006,PAUL VENZAC,PAUL VENZAC,0,"616115,121043879","123445,333367519",O,1,0
79304,54,174,103,54,54,103,5,5,01/01/2006,77118,1228806,5,01/01/2006,Les Fortes T,Les Fortes Terres,0,"625701,108430673","137655,252644822",O,1,0
79305,14,141,494,14,147,494,5,5,01/01/2006,93073,-1,5,01/01/2006,HUB POSTAL,HUB POSTAL,?,"615307,27904961","143399,756129403",N,1,0
79306,62,162,244,62,62,244,6,6,01/07/2011,77280,1315935,6,01/07/2011,CROIX BLANCH,CROIX BLANCHE,0,"621793,841791459","93598,2515272603",O,1,0
79307,10,110,59511,10,10,59511,5,5,01/01/2006,91549,1832539,5,01/01/2006,Claire Joie,Claire Joie,0,"597587,003299347","105321,145232818",O,1,0
79308,13,113,10519,13,13,10519,5,5,01/01/2006,78168,-1,5,01/01/2006,Les Fontaine,Les Fontaine,?,"569899,043220157","116608,337214292",N,1,0
79309,140,140,192,40,40,192,5,5,01/01/2006,77296,-1,5,01/01/2006,Gare Lieusai,Gare Lieusai,?,"617261,107264193","103122,128869076",N,1,0
79310,193,100,36868,193,293,36868,4,4,01/01/2006,-1,-1,4,01/01/2006,36868,36868,?,"616988,443650252","140716,811558468",N,1,0
79311,136,117,349,136,97,349,6,6,01/07/2011,77192,-1,6,01/07/2011,FONTENAY,FONTENAY-TRESIGNY BOULEVARD HARDY,0,"638612,996708815","112138,675728584",O,1,0
79312,001,3,0030010753007,987,100,0030010753007,3,3,01/01/2006,92050,-1,3,01/01/2006,SADI-CARNOT-JO,SADI-CARNOT-JOLIOT-CURIE,?,"590275,987242363","132090,673224313",N,1,0
79313,8,184,442,608,84,442,8,8,01/07/2011,77431,-1,8,01/07/2011,Maison de re,Maison de re,?,"626569,439776681","62290,7450807658",N,1,0
79314,230,127,10,410,27,10,3,3,01/01/2006,92023,-1,3,01/01/2006,Mail Plaine,Mail Plaine,?,"593442,461586861","120341,197662486",N,1,0
79315,87,165,95,487,65,95,5,5,01/01/2006,77250,2285263,5,01/01/2006,PARISUD ESPA,ZAE ESPAGNE,0,"615523,616462596","104714,271964754",O,1,0
79316,001,3,0030010152045,100,100,0030010152045,3,3,01/01/2006,93027,-1,3,01/01/2006,8 MAI 1945-MET,8 MAI 1945-METRO,0,"605620,381041192","135865,060357149",O,1,0
79317,97,117,128,97,97,128,8,8,01/07/2011,77030,6878,8,01/07/2011,,Place,0,"671992,453004472","128951,604888438",O,1,0
79318,57,157,289,57,57,289,6,6,01/07/2011,78314,1455657,6,01/07/2011,,Charvets,0,"560627,680141118","143791,418078571",O,1,0
79319,8,164,50,608,64,50,7,7,01/07/2011,77048,2285533,7,01/07/2011,SQUARE THIBA,SQUARE THIBAULT,0,"628074,330398038","71751,8101392938",O,1,0
79320,24,124,1152,24,24,1152,5,5,01/01/2006,91435,278510,5,01/01/2006,Cie des Eaux,Compagnie des Eaux,0,"611373,961178061","97170,7462180511",O,1,0
79322,193,100,37371,193,293,37371,4,4,01/01/2006,-1,-1,4,01/01/2006,37371,37371,?,"616988,443650252","140716,811558468",N,1,0
79323,149,120,31500,149,20,31500,3,3,01/01/2006,92071,923868,3,01/01/2006,Les Musicien,Les Musiciens,0,"597788,168453824","120400,024486425",O,1,0
79325,193,100,37236,193,293,37236,4,4,01/01/2006,-1,-1,4,01/01/2006,37236,37236,?,"616988,443650252","140716,811558468",N,1,0
79326,149,120,30421,149,20,30421,3,3,01/01/2006,92019,923760,3,01/01/2006,Chateaubrian,Chateaubriand,0,"595033,585493287","119372,637125278",O,1,0
79328,193,100,37645,193,293,37645,4,4,01/01/2006,-1,-1,4,01/01/2006,37645,37645,?,"616988,443650252","140716,811558468",N,1,0
79329,193,100,25380,193,293,25380,4,4,01/01/2006,93005,-1,4,01/01/2006,POISSONS,POISSONS,0,"612284,727686037","139797,917178056",O,1,0

In [35]:
bus_202 = arrets[arrets['COD_TLB_ARRT_STTN'] == '0030030301200']

In [33]:
get_counts(arrets['COD_TLB_ARRT_STTN'])

{'1133         ': 13,
 '3244         ': 2,
 '35808        ': 1,
 '16161        ': 1,
 '8320         ': 2,
 '0030010068064': 1,
 '0030010763006': 1,
 '33           ': 57,
 '524          ': 21,
 '45479        ': 1,
 '0030010166009': 1,
 '360          ': 34,
 '1471         ': 10,
 '50828        ': 1,
 '253          ': 33,
 '28242        ': 1,
 '0030010098019': 1,
 '0030010184027': 1,
 '58801        ': 2,
 '268          ': 25,
 '1114         ': 15,
 '50755        ': 1,
 '0030010743038': 1,
 '44           ': 56,
 '1344         ': 13,
 '0030010299028': 1,
 '115          ': 47,
 '36594        ': 1,
 '36           ': 56,
 '338          ': 39,
 '347          ': 42,
 '307          ': 32,
 '556          ': 19,
 '0030010116012': 1,
 '329          ': 34,
 '53571        ': 1,
 '45117        ': 1,
 '1436         ': 9,
 '575          ': 22,
 '558          ': 19,
 '38           ': 54,
 '279          ': 29,
 '0030010157020': 1,
 '0030010396008': 1,
 '34           ': 60,
 '99           ': 45,
 '3146         ': 3,
 '2110         ': 4,
 '32095        ': 1,
 '0030010292059': 1,
 '10259        ': 1,
 '802          ': 10,
 '0030010391008': 1,
 '0030010260022': 1,
 '0030010069046': 1,
 '168          ': 43,
 '404          ': 23,
 '107          ': 47,
 '0030010714093': 1,
 '468          ': 23,
 '529          ': 18,
 '0030010524004': 1,
 '0030010927030': 1,
 '10283        ': 3,
 '1311         ': 14,
 '46321        ': 1,
 '1083         ': 12,
 '1302         ': 15,
 '40133        ': 1,
 '0030010574009': 1,
 '22           ': 71,
 '30614        ': 1,
 '3215         ': 3,
 '769          ': 13,
 '483          ': 22,
 '0030010018010': 1,
 '0030030090700': 1,
 '8361         ': 2,
 '57           ': 51,
 '2332         ': 1,
 '1375         ': 7,
 '0030010734001': 1,
 '320          ': 37,
 '0030010574031': 1,
 '45877        ': 1,
 '65380        ': 1,
 '0030010249029': 1,
 '45           ': 59,
 '370          ': 35,
 '0030010761075': 1,
 '0030010234052': 1,
 '5470         ': 1,
 '0030010086055': 1,
 '2000         ': 7,
 '19120        ': 3,
 '20033        ': 1,
 '250          ': 42,
 '0030010269051': 1,
 '37928        ': 1,
 '0030010238103': 1,
 '446          ': 27,
 '0030010712117': 1,
 '1613         ': 4,
 '195          ': 39,
 '359          ': 27,
 '19503        ': 2,
 '1514         ': 4,
 '0030010186035': 1,
 '0030010702024': 1,
 '35692        ': 1,
 '1291         ': 17,
 '412          ': 29,
 '0030010131013': 1,
 '344          ': 38,
 '0030010259014': 1,
 '36224        ': 1,
 '48           ': 55,
 '0030010367040': 1,
 '0030010017069': 1,
 '393009       ': 1,
 '1367         ': 10,
 '193          ': 40,
 '0030010137002': 1,
 '196          ': 38,
 '3260         ': 3,
 '517          ': 28,
 '0030010250031': 1,
 '0030010744046': 1,
 '1091         ': 12,
 '1336         ': 9,
 '861          ': 8,
 '0030010378034': 1,
 '37443        ': 1,
 '0030010290026': 1,
 '317          ': 37,
 '357          ': 28,
 '0030010340007': 1,
 '183          ': 50,
 '0030010541034': 1,
 '0030010546034': 1,
 '1143         ': 12,
 '0030010181035': 1,
 '653          ': 9,
 '19534        ': 1,
 '104          ': 46,
 '1117         ': 16,
 '50513        ': 1,
 '139          ': 42,
 '0030010097016': 1,
 '0030010216025': 1,
 '0030010169015': 1,
 '135          ': 51,
 '271          ': 39,
 '129          ': 46,
 '198          ': 48,
 '2783         ': 4,
 '464          ': 27,
 '20182        ': 1,
 '0030010250045': 1,
 '12           ': 82,
 '1570         ': 7,
 '29           ': 64,
 '328          ': 33,
 '0030010721135': 1,
 '241          ': 39,
 '30080        ': 1,
 '52           ': 47,
 '0030010274011': 1,
 '554          ': 20,
 '613          ': 27,
 '424          ': 25,
 '0030010535011': 1,
 '18133        ': 2,
 '0030010068014': 1,
 '795          ': 7,
 '586          ': 20,
 '530          ': 21,
 '0030010585004': 1,
 '1157         ': 14,
 '0030030130100': 1,
 '109          ': 47,
 '184          ': 44,
 '0030010556019': 1,
 '110          ': 50,
 '635          ': 21,
 '345          ': 32,
 '0030010544007': 1,
 '50752        ': 1,
 '691          ': 15,
 '1147         ': 13,
 '0030010330044': 1,
 '19454        ': 3,
 '0030010303004': 1,
 '23780        ': 1,
 '1146         ': 14,
 '815          ': 6,
 '0030010576027': 1,
 '216          ': 35,
 '0030010731139': 1,
 '0030010026072': 1,
 '0030010098053': 1,
 '1267         ': 14,
 '37           ': 55,
 '0030010393024': 1,
 '0030010741024': 1,
 '19126        ': 2,
 '2001         ': 8,
 '1604         ': 2,
 '36148        ': 1,
 '0030010742002': 1,
 '0030010212050': 1,
 '40140        ': 1,
 '754          ': 10,
 '0030010080015': 1,
 '16           ': 79,
 '19524        ': 1,
 '37696        ': 1,
 '19468        ': 1,
 '1256         ': 14,
 '0030010174098': 1,
 '407          ': 29,
 '0030010080065': 1,
 '0030010291010': 1,
 '1368         ': 10,
 '0030010715100': 1,
 '0030010194045': 1,
 '0030010133062': 1,
 '0030010169065': 1,
 '437          ': 33,
 '19529        ': 1,
 '0030010039064': 1,
 '258          ': 33,
 '0030010715041': 1,
 '0030010039014': 1,
 '582          ': 23,
 '0030010195028': 1,
 '0030010358067': 1,
 '605          ': 24,
 '0030010762072': 1,
 '1014         ': 19,
 '0030010238107': 1,
 '178          ': 38,
 '0030010249007': 1,
 '0030010171042': 1,
 '0030010075039': 1,
 '711          ': 17,
 '51031        ': 1,
 '36219        ': 1,
 '5902         ': 1,
 '0030010117037': 1,
 '3            ': 83,
 '0030010138004': 1,
 '1248         ': 13,
 '0030010379014': 1,
 '0030010920014': 1,
 '0030010361079': 1,
 '1053         ': 8,
 '1101         ': 13,
 '0030010289014': 1,
 '27231        ': 1,
 '10           ': 84,
 '690          ': 15,
 '333          ': 28,
 '0030010753049': 1,
 '0030010702005': 1,
 '1582         ': 9,
 '680          ': 17,
 '0030010269073': 1,
 '0030010176042': 1,
 '113          ': 48,
 '0030010921054': 1,
 '0030010111012': 1,
 '49           ': 56,
 '0030010566028': 1,
 '0030010367035': 1,
 '0030010111062': 1,
 '25           ': 68,
 '35852        ': 1,
 '1320         ': 7,
 '0030010302031': 1,
 '266          ': 31,
 '694          ': 17,
 '0030010092023': 1,
 '316          ': 33,
 '0030010262054': 1,
 '145          ': 46,
 '55           ': 48,
 '0030010133012': 1,
 '442          ': 24,
 '243          ': 33,
 '336          ': 29,
 '1224         ': 7,
 '86           ': 44,
 '50600        ': 5,
 '0030010131063': 1,
 '1985         ': 4,
 '39           ': 52,
 '187          ': 41,
 '469          ': 21,
 '0030010074004': 1,
 '1314         ': 10,
 '78           ': 47,
 '36231        ': 1,
 '0030010123051': 1,
 '0030010105011': 1,
 '2447         ': 1,
 '0030010185055': 1,
 '0030010350030': 1,
 '77           ': 47,
 '531          ': 21,
 '40196        ': 1,
 '0030010199013': 1,
 '905          ': 7,
 '2295         ': 2,
 '1362         ': 10,
 '0030010355001': 1,
 '0030010017057': 1,
 '124          ': 46,
 '102          ': 48,
 '1196         ': 10,
 '0030010920064': 1,
 '37135        ': 1,
 '17           ': 73,
 '0030010261002': 1,
 '20144        ': 1,
 '1602         ': 4,
 '0030010741005': 1,
 '0030010119058': 1,
 '1180         ': 16,
 '0030010278017': 1,
 '2711         ': 2,
 '0030010301052': 1,
 '491          ': 30,
 '356          ': 37,
 '677          ': 13,
 '688          ': 14,
 '0030010358017': 1,
 '0030010007048': 1,
 '27887        ': 2,
 '1017         ': 15,
 '0030010060011': 1,
 '45280        ': 1,
 '0030010563025': 1,
 '136          ': 42,
 '32           ': 64,
 '37905        ': 1,
 '0030010058042': 1,
 '1154         ': 14,
 '61501        ': 1,
 '1106         ': 18,
 '427          ': 29,
 '21           ': 70,
 '35840        ': 1,
 '0030010199017': 1,
 '18062        ': 2,
 '1041         ': 19,
 '0030010092027': 1,
 '421          ': 30,
 '260          ': 33,
 '38120        ': 1,
 '8293         ': 3,
 '19340        ': 1,
 '0030010341009': 1,
 '0030010259064': 1,
 '45509        ': 1,
 '19065        ': 2,
 '289          ': 33,
 '0030010571027': 1,
 '0030010020024': 1,
 '137          ': 51,
 '428          ': 28,
 '0030010161009': 1,
 '0030010713115': 1,
 '1049         ': 11,
 '2055         ': 4,
 '0030010187020': 1,
 '0030010393005': 1,
 '0030010254010': 1,
 '0030010206050': 1,
 '0030010096028': 1,
 '455          ': 22,
 '98           ': 48,
 '5393         ': 2,
 '0030010123020': 1,
 '0030010043002': 1,
 '1042         ': 20,
 '853          ': 13,
 '0030010070029': 1,
 '0030010047043': 1,
 '0030010052035': 1,
 '0030010713096': 1,
 '633          ': 19,
 '561          ': 22,
 '19128        ': 2,
 '0030010153026': 1,
 '37563        ': 1,
 '0030010056014': 1,
 '0030010360052': 1,
 '0030010714048': 1,
 '0030010732015': 1,
 '1145         ': 15,
 '163          ': 43,
 '750          ': 16,
 '0030050181004': 1,
 '378          ': 28,
 '8059         ': 2,
 '549          ': 14,
 '0030030251500': 1,
 '0030010714106': 1,
 '0030010354008': 1,
 '0030010186040': 1,
 '636          ': 17,
 '0030010117033': 1,
 '22593        ': 1,
 '386003       ': 1,
 '222          ': 40,
 '546          ': 19,
 '0030010174019': 1,
 '30164        ': 2,
 '0030010251044': 1,
 '0030010341031': 1,
 '429          ': 27,
 '797          ': 10,
 '1611         ': 7,
 '151          ': 46,
 '0030010790011': 1,
 '0030010399058': 1,
 '0030010187051': 1,
 '2443         ': 3,
 '164798       ': 1,
 '0030010796051': 1,
 '1100         ': 18,
 '966          ': 7,
 '138          ': 46,
 '0030010289090': 1,
 '0030010586019': 1,
 '8            ': 80,
 '0030010214004': 1,
 '150          ': 44,
 '1262         ': 13,
 '726          ': 16,
 '1372         ': 9,
 '0030010346009': 1,
 '0030010389009': 1,
 '51           ': 53,
 '0030010173028': 1,
 '0030010713165': 1,
 '0030010194032': 1,
 '172          ': 39,
 '46290        ': 1,
 '3199         ': 2,
 '1161         ': 10,
 '31591        ': 1,
 '38994        ': 1,
 '310          ': 38,
 '0030010278013': 1,
 '758          ': 11,
 '51160        ': 1,
 '0030010070007': 1,
 '286          ': 28,
 '37832        ': 1,
 '0030010027018': 1,
 '0030010175009': 1,
 '288          ': 28,
 '0030010520003': 1,
 '0030010094052': 1,
 '111          ': 51,
 '0030010275001': 1,
 '0030010267042': 1,
 '175          ': 46,
 '50611        ': 1,
 '789          ': 8,
 '2184         ': 2,
 '0030010208032': 1,
 '0030010017019': 1,
 '395          ': 36,
 '1546         ': 4,
 '38082        ': 1,
 '0030010098057': 1,
 '0030010295036': 1,
 '80           ': 45,
 '0030010060061': 1,
 '1295         ': 11,
 '354          ': 32,
 '0030010030031': 1,
 '0030010796020': 1,
 '0030010174057': 1,
 '19557        ': 1,
 '0030010713159': 1,
 '45013        ': 1,
 '0030010391012': 1,
 '297          ': 31,
 '2302         ': 3,
 '18051        ': 2,
 '35043        ': 1,
 '0030010358063': 1,
 '0030010724013': 1,
 '0030010291006': 1,
 '0030010924011': 1,
 '0030010714097': 1,
 '0030010081014': 1,
 '18074        ': 2,
 '20085        ': 1,
 '294          ': 33,
 '0030010056064': 1,
 '0030010370031': 1,
 '326          ': 30,
 '600          ': 34,
 '0030010131017': 1,
 '6837         ': 1,
 '35065        ': 1,
 '557          ': 20,
 '46301        ': 1,
 '7528         ': 1,
 '54271        ': 1,
 '66           ': 49,
 '123          ': 42,
 '64           ': 46,
 '230          ': 36,
 '978          ': 12,
 '901          ': 9,
 '386          ': 35,
 '0030010147010': 1,
 '54131        ': 1,
 '30710        ': 1,
 '0030010289105': 1,
 '82           ': 40,
 '4126         ': 1,
 '0030010268044': 1,
 '0030010714037': 1,
 '9030         ': 5,
 '125          ': 43,
 '0030010020005': 1,
 '97           ': 48,
 '67           ': 46,
 '0030010080059': 1,
 '0030010269020': 1,
 '46           ': 55,
 '0030010396012': 1,
 '19442        ': 1,
 '0030010206041': 1,
 '6002         ': 2,
 '217          ': 35,
 '36173        ': 1,
 '53           ': 48,
 '0030010308030': 1,
 '0030010244028': 1,
 '0030010185014': 1,
 '0030010721140': 1,
 '18032        ': 2,
 '214          ': 41,
 '471          ': 26,
 '0030010771004': 1,
 '601          ': 31,
 '142          ': 40,
 '14561        ': 1,
 '35981        ': 1,
 '0030010580013': 1,
 '9499         ': 1,
 '0030010385001': 1,
 '38069        ': 1,
 '1067         ': 11,
 '0030010070003': 1,
 '0030010312052': 1,
 '43           ': 56,
 '0030010389031': 1,
 '26           ': 64,
 '0030010358013': 1,
 '0030010212041': 1,
 '116          ': 48,
 '702          ': 14,
 '334          ': 31,
 '580          ': 22,
 '0030010086014': 1,
 '0030010116062': 1,
 '276          ': 35,
 '0030010144067': 1,
 '509          ': 29,
 '0030010091028': 1,
 '68           ': 46,
 '642          ': 15,
 '41362        ': 1,
 '0030010289064': 1,
 '0030010318041': 1,
 '489          ': 32,
 '8030         ': 2,
 '0030010220146': 1,
 '0030010268068': 1,
 '0030010295047': 1,
 '0030010320088': 1,
 '0030010256018': 1,
 '0030010302045': 1,
 '1376         ': 8,
 '0030010177050': 1,
 '0030010175076': 1,
 '0030010720046': 1,
 '3341         ': 3,
 '0030010178024': 1,
 '571          ': 21,
 '921          ': 8,
 '36116        ': 1,
 '9688         ': 1,
 '0030010396062': 1,
 '0030010712079': 1,
 '35155        ': 1,
 '59           ': 49,
 '337          ': 37,
 '0030010183026': 1,
 '16928        ': 1,
 '3093         ': 3,
 '944          ': 4,
 '61           ': 50,
 '96           ': 43,
 '0030010210029': 1,
 '37465        ': 1,
 '0030010310015': 1,
 '477          ': 26,
 '0030010185064': 1,
 '0030010072041': 1,
 '2576         ': 2,
 '37149        ': 1,
 '2004         ': 5,
 '0030010256068': 1,
 '0030010791020': 1,
 '2771         ': 2,
 '788          ': 10,
 '37856        ': 1,
 '0030010047047': 1,
 '368          ': 32,
 '850          ': 10,
 '212          ': 46,
 '0030010318042': 1,
 '37974        ': 1,
 '445          ': 29,
 '0030030121400': 1,
 '19430        ': 1,
 '684217       ': 1,
 '50           ': 54,
 '1070         ': 15,
 '51670        ': 1,
 '264          ': 38,
 '0030010066020': 1,
 '0030010388017': 1,
 '143          ': 34,
 '0030010157052': 1,
 '101          ': 48,
 '18119        ': 1,
 '9220         ': 2,
 '56           ': 49,
 '0030010333014': 1,
 '0030010160007': 1,
 '1257         ': 14,
 '58080        ': 1,
 '55490        ': 1,
 '10643        ': 1,
 '1349         ': 16,
 '30040        ': 2,
 '30           ': 70,
 '20219        ': 1,
 '0030010513011': 1,
 '847          ': 6,
 '0030010346045': 1,
 '0030010530036': 1,
 '233          ': 35,
 '0030010390056': 1,
 '20284        ': 1,
 '0030010048039': 1,
 '73           ': 49,
 '71           ': 55,
 '0030010515005': 1,
 '0030010238038': 1,
 '0030010530043': 1,
 '0030010279031': 1,
 '0030010144017': 1,
 '0030010174053': 1,
 '1038         ': 15,
 '36691        ': 1,
 '1077         ': 12,
 '158          ': 37,
 '38159        ': 1,
 '776          ': 14,
 '0030010732065': 1,
 '0030010306052': 1,
 '619          ': 13,
 '11005        ': 1,
 '0030010054028': 1,
 '0030010399026': 1,
 '134          ': 42,
 '22277        ': 1,
 '14829        ': 1,
 '169          ': 41,
 '0030010361094': 1,
 '192          ': 40,
 '313          ': 30,
 '1097         ': 11,
 '384          ': 34,
 '185          ': 43,
 '0030010589034': 1,
 '27967        ': 1,
 '19588        ': 2,
 '91           ': 43,
 '0030010007033': 1,
 '0030010535008': 1,
 '1331         ': 10,
 '0030010111099': 1,
 '303          ': 33,
 '13           ': 84,
 '0030010104044': 1,
 '53001        ': 1,
 '0030010017053': 1,
 '1498         ': 10,
 '682252       ': 1,
 '1148         ': 11,
 '0030010268018': 1,
 '298          ': 32,
 '2620         ': 2,
 '934          ': 6,
 '11915        ': 1,
 '140          ': 44,
 '0030010161031': 1,
 '0030010144013': 1,
 '0030010150039': 1,
 '0030010147120': 1,
 '45675        ': 1,
 '10519        ': 2,
 '805          ': 11,
 '45057        ': 1,
 '23           ': 67,
 '0030010579017': 1,
 '261          ': 34,
 '0030010211009': 1,
 '3156         ': 3,
 '0030010027044': 1,
 '623          ': 16,
 '738          ': 15,
 '5333         ': 2,
 '0030010032017': 1,
 '539          ': 16,
 '1713         ': 2,
 '417          ': 25,
 '226          ': 33,
 '0030010239044': 1,
 '0030010166045': 1,
 '924          ': 8,
 '577          ': 22,
 '282          ': 27,
 '1126         ': 11,
 '3144         ': 2,
 '461          ': 31,
 '0030010302032': 1,
 '0030010207021': 1,
 '0030010028023': 1,
 '60           ': 47,
 '0030010104018': 1,
 '0030010239018': 1,
 '0030010183058': 1,
 '283          ': 35,
 '19138        ': 2,
 '19164        ': 1,
 '153          ': 46,
 '5004         ': 3,
 '314          ': 30,
 '0030010030045': 1,
 '52941        ': 1,
 '418          ': 24,
 '0030010234035': 1,
 '0030010122056': 1,
 '0030010088042': 1,
 '5030         ': 4,
 '53320        ': 1,
 '204          ': 43,
 '51970        ': 1,
 '0030010061020': 1,
 '0030010301040': 1,
 '49971        ': 1,
 '89           ': 43,
 '205          ': 40,
 '5851         ': 3,
 '53560        ': 2,
 '240          ': 38,
 '252          ': 38,
 '1170         ': 14,
 '219          ': 35,
 '0030010330018': 1,
 '51500        ': 2,
 '58           ': 53,
 '15           ': 85,
 '0030010024021': 1,
 '0030010724063': 1,
 '0030010174069': 1,
 '538          ': 20,
 '579          ': 21,
 '156          ': 36,
 '45088        ': 1,
 '0030010047036': 1,
 '5987         ': 1,
 '0030010145007': 1,
 '506          ': 21,
 '0030010148025': 1,
 '0030010762004': 1,
 '0030010735043': 1,
 '0030010220028': 1,
 '5            ': 86,
 '0030010299056': 1,
 '17380        ': 1,
 '0030010714033': 1,
 '1140         ': 17,
 '0030010745113': 1,
 '75           ': 44,
 '0030010021004': 1,
 '1171         ': 10,
 '35924        ': 1,
 '0030010732089': 1,
 '510          ': 33,
 '658          ': 14,
 '1087         ': 11,
 '29511        ': 1,
 '0030010249003': 1,
 '6639         ': 1,
 '0030010559034': 1,
 '20346        ': 1,
 '0030010162042': 1,
 '0030010530047': 1,
 '300          ': 38,
 '45611        ': 1,
 '47           ': 58,
 '291          ': 31,
 '32991        ': 1,
 '149          ': 41,
 '534          ': 15,
 '0030010120017': 1,
 '51030        ': 2,
 '0030010102021': 1,
 '0030010501016': 1,
 '610          ': 25,
 '771          ': 18,
 '855          ': 10,
 '761          ': 11,
 '2048         ': 5,
 '523          ': 23,
 '165          ': 40,
 '148          ': 42,
 '35741        ': 1,
 '281          ': 30,
 '755          ': 9,
 '0030010046029': 1,
 '0030010515024': 1,
 '1            ': 84,
 '10239        ': 2,
 '982          ': 9,
 '1221         ': 14,
 '0030010274008': 1,
 '0030010320111': 1,
 '37305        ': 1,
 '32640        ': 1,
 '439          ': 30,
 '0030010143158': 1,
 '0030010032013': 1,
 '19428        ': 2,
 '0030010279009': 1,
 '36295        ': 1,
 '0030010164058': 1,
 '5335         ': 2,
 '0030010125004': 1,
 '295          ': 33,
 '3276         ': 4,
 '0030010110033': 1,
 '1155         ': 10,
 '1055         ': 11,
 '443          ': 24,
 '465          ': 28,
 '1234         ': 10,
 '0030010174103': 1,
 '122          ': 45,
 '1525         ': 4,
 '40120        ': 1,
 '0030010389045': 1,
 '481          ': 26,
 '0030010144063': 1,
 '0030010105012': 1,
 '0030010372017': 1,
 '0030010711084': 1,
 '304          ': 35,
 '35314        ': 1,
 '0030010272034': 1,
 '0030010145029': 1,
 '3247         ': 1,
 '4056         ': 2,
 '0030010251018': 1,
 '0030010520007': 1,
 '1682         ': 3,
 '0030010594048': 1,
 '0030010394034': 1,
 '0030010325043': 1,
 '383          ': 31,
 '0030010594056': 1,
 '0030010304023': 1,
 '1402         ': 11,
 '14441        ': 1,
 '697          ': 16,
 '516          ': 34,
 '1965         ': 1,
 '322          ': 31,
 '498          ': 25,
 '51790        ': 2,
 '0030010112049': 1,
 '0030010105008': 1,
 '1026         ': 12,
 '5021         ': 1,
 '18           ': 67,
 '331          ': 33,
 '0030010751028': 1,
 '45409        ': 1,
 '36967        ': 1,
 '474          ': 20,
 '352          ': 32,
 '269          ': 39,
 '119          ': 39,
 '0030010093025': 1,
 '0030010147060': 1,
 '0030010191036': 1,
 '0030010042006': 1,
 '6011         ': 1,
 '0030010790012': 1,
 '0030010114034': 1,
 '1244         ': 11,
 '1330         ': 11,
 '0030010143126': 1,
 '0030010526009': 1,
 '116244       ': 1,
 '1542         ': 5,
 '0030010076009': 1,
 '0030010031044': 1,
 '0030010143016': 1,
 '238          ': 32,
 '0030010722055': 1,

In [36]:
bus_202

,COD_TLB_RES,COD_TLB_TRNS,COD_TLB_ARRT_STTN,COD_STF_RES,COD_STF_TRNS,COD_STF_ARRT_STTN,ZONS_ARRT,COD_ZON_PHSQ_MIN,DAT_DEBT_VALD_ZON_PHSQ_MIN,COD_INS_COMM,COD_ARRT_COMM,COD_ZON_PHSQ_MAX,DAT_DEBT_VALD_ZON_PHSQ_MAX,LIBL_COUR_ARRT_STTN,LIBL_LONG_ARRT_STTN,POL_PDU,COOR_X_PHSQ,COOR_Y_PHSQ,CORR_DONN_STF,MOD_BUS,MOD_RER
46994,001,3,0030030301200,110,100,342,1,1,01/01/2006,75118,342,1,01/01/2006,GUY MOQUET,GUY MOQUET,0,"599333,101","132488,688",O,0,0

In [12]:
arrets[arrets['COD_TLB_RES'] == '005']

Empty DataFrame
Columns: [COD_TLB_RES, COD_TLB_TRNS, COD_TLB_ARRT_STTN, COD_STF_RES, COD_STF_TRNS, COD_STF_ARRT_STTN, ZONS_ARRT, COD_ZON_PHSQ_MIN, DAT_DEBT_VALD_ZON_PHSQ_MIN, COD_INS_COMM, COD_ARRT_COMM, COD_ZON_PHSQ_MAX, DAT_DEBT_VALD_ZON_PHSQ_MAX, LIBL_COUR_ARRT_STTN, LIBL_LONG_ARRT_STTN, POL_PDU, COOR_X_PHSQ, COOR_Y_PHSQ, CORR_DONN_STF, MOD_BUS, MOD_RER]
Index: []

In [13]:
bus_202 = bus_202[~bus_202.LIBL_LONG_ARRT_STTN.duplicated(keep='first')] #C'est genial

In [14]:
bus_202

,COD_TLB_RES,COD_TLB_TRNS,COD_TLB_ARRT_STTN,COD_STF_RES,COD_STF_TRNS,COD_STF_ARRT_STTN,ZONS_ARRT,COD_ZON_PHSQ_MIN,DAT_DEBT_VALD_ZON_PHSQ_MIN,COD_INS_COMM,COD_ARRT_COMM,COD_ZON_PHSQ_MAX,DAT_DEBT_VALD_ZON_PHSQ_MAX,LIBL_COUR_ARRT_STTN,LIBL_LONG_ARRT_STTN,POL_PDU,COOR_X_PHSQ,COOR_Y_PHSQ,CORR_DONN_STF,MOD_BUS,MOD_RER
70,001,3,0030010714093,987,100,0030010714093,3,3,01/01/2006,92007,20145,3,01/01/2006,MARCEL BONNET,MARCEL BONNET,0,"598889,597335722","121694,320817214",O,1,0

In [15]:
arrets[arrets['COD_TLB_RES'] == '1  ']

,COD_TLB_RES,COD_TLB_TRNS,COD_TLB_ARRT_STTN,COD_STF_RES,COD_STF_TRNS,COD_STF_ARRT_STTN,ZONS_ARRT,COD_ZON_PHSQ_MIN,DAT_DEBT_VALD_ZON_PHSQ_MIN,COD_INS_COMM,COD_ARRT_COMM,COD_ZON_PHSQ_MAX,DAT_DEBT_VALD_ZON_PHSQ_MAX,LIBL_COUR_ARRT_STTN,LIBL_LONG_ARRT_STTN,POL_PDU,COOR_X_PHSQ,COOR_Y_PHSQ,CORR_DONN_STF,MOD_BUS,MOD_RER
857,1,126,303,501,501,303,4,4,01/01/2006,95199,-1,4,01/01/2006,DOJAUR,DOJAUR,0,"600259,809184176","148111,493694073",O,1,0
2212,1,126,322,501,501,322,4,4,01/01/2006,95199,-1,4,01/01/2006,DOPOS1,DOPOS1,?,"599860,103001054","147827,702033466",N,1,0
6137,1,126,275,501,501,275,4,4,01/01/2006,95199,-1,4,01/01/2006,DOCHE1,DOCHE1,?,"599082,669945957","147326,07221845",N,1,0
7894,1,126,311,501,501,311,4,4,01/01/2006,95199,-1,4,01/01/2006,DOMARL,DOMARL,0,"600116,914227637","148228,407412286",O,1,0
9181,1,126,328,501,501,328,4,4,01/01/2006,95199,-1,4,01/01/2006,DOROUZ,DOROUZ,?,"599204,585873757","148149,467868347",N,1,0
9631,1,126,319,501,501,319,4,4,01/01/2006,95199,-1,4,01/01/2006,DOOMB1,DOOMB1,0,"598722,935209909","147605,870655129",O,1,0
17136,1,126,280,501,501,280,4,4,01/01/2006,95199,-1,4,01/01/2006,DOCLI1,DOCLI1,0,"599211,574902005","147165,188729429",O,1,0
18210,1,126,305,501,501,305,4,4,01/01/2006,95199,-1,4,01/01/2006,DOJON2,DOJON2,0,"598796,879275194","147406,016116133",O,1,0
19344,1,126,316,501,501,316,4,4,01/01/2006,95199,-1,4,01/01/2006,DONECK,DONECK,?,"599957,032043463","148320,339609199",N,1,0
20593,1,126,295,501,501,295,4,4,01/01/2006,95199,-1,4,01/01/2006,DOFOU2,DOFOU2,?,"598454,13763832","148093,515640764",N,1,0
29361,1,126,333,501,501,333,4,4,01/01/2006,95199,-1,4,01/01/2006,DOTOUR,DOTOUR,?,"599814,13754724","148416,26895951",N,1,0
32213,1,126,317,501,501,317,4,4,01/01/2006,95199,-1,4,01/01/2006,DONOR1,DONOR1,0,"599743,18783717","147338,060555747",O,1,0
32430,1,126,274,501,501,274,4,4,01/01/2006,95199,-1,4,01/01/2006,DOBRET,DOBRET,0,"599243,554957399","147756,756142192",O,1,0
35574,1,126,325,501,501,325,4,4,01/01/2006,95199,-1,4,01/01/2006,DOREP2,DOREP2,0,"599119,642153016","147204,160899793",O,1,0
37718,1,126,31,501,501,31,4,4,01/01/2006,95199,-1,4,01/01/2006,GARE DE DOMO,GARE DE DOMO,?,"600080,940854557","148022,558876226",N,1,0
42382,1,126,300,501,501,300,4,4,01/01/2006,95199,-1,4,01/01/2006,DOGER2,DOGER2,0,"600197,855580492","147566,893206115",O,1,0
46041,1,126,294,501,501,294,4,4,01/01/2006,95199,-1,4,01/01/2006,DOFOU1,DOFOU1,?,"598461,132630733","148105,506737465",N,1,0
46790,1,126,304,501,501,304,4,4,01/01/2006,95199,-1,4,01/01/2006,DOJON1,DOJON1,0,"598799,87714819","147413,010978948",O,1,0
46845,1,126,290,501,501,290,4,4,01/01/2006,95199,-1,4,01/01/2006,DOFER1,DOFER1,0,"598516,089499844","147863,683822892",O,1,0
48882,1,126,36,501,501,36,4,4,01/01/2006,95199,-1,4,01/01/2006,LES FOUGERES,LES FOUGERES,?,"598384,189559265","148131,488529412",N,1,0
49040,1,126,269,501,501,269,4,4,01/01/2006,95199,-1,4,01/01/2006,DOBODE,DOBODE,0,"599427,423640345","148568,157862555",O,1,0
59565,1,126,320,501,501,320,4,4,01/01/2006,95199,-1,4,01/01/2006,DOOMB2,DOOMB2,0,"598700,951361232","147611,866478498",O,1,0
59790,1,126,276,501,501,276,4,4,01/01/2006,95199,-1,4,01/01/2006,DOCHE2,DOCHE2,0,"598985,740651877","147320,07729707",O,1,0
60330,1,126,309,501,501,309,4,4,01/01/2006,95199,-1,4,01/01/2006,DOMAI1,DOMAI1,?,"599317,499197626","147454,976654506",N,1,0
60484,1,126,324,501,501,324,4,4,01/01/2006,95199,-1,4,01/01/2006,DOREP1,DOREP1,0,"599127,63636439","147210,156476204",O,1,0
62198,1,126,291,501,501,291,4,4,01/01/2006,95199,-1,4,01/01/2006,DOFER2,DOFER2,0,"598507,096145466","147867,680989564",O,1,0
63150,1,126,299,501,501,299,4,4,01/01/2006,95199,-1,4,01/01/2006,DOGER1,DOGER1,0,"600203,851187157","147570,890290277",O,1,0
65608,1,126,302,501,501,302,4,4,01/01/2006,95199,-1,4,01/01/2006,DOINDE,DOINDE,?,"599856,105610025","147527,921648162",N,1,0
65702,1,126,37,501,501,37,4,4,01/01/2006,95199,-1,4,01/01/2006,LES FOUGERES,LES FOUGERES,?,"598398,179215127","148127,491302202",N,1,0
65958,1,126,292,501,501,292,4,4,01/01/2006,95199,-1,4,01/01/2006,DOFOS1,DOFOS1,?,"600011,991588125","147524,923763719",N,1,0
72706,1,126,306,501,501,306,4,4,01/01/2006,95199,-1,4,01/01/2006,DOLONG,DOLONG,?,"599664,248510395","148546,173305205",N,1,0
72817,1,126,298,501,501,298,4,4,01/01/2006,95199,-1,4,01/01/2006,DOGAR3,DOGAR3,0,"600088,934986933","148008,569165266",O,1,0
74021,1,126,314,501,501,314,4,4,01/01/2006,95199,-1,4,01/01/2006,DOMON1,DOMON1,0,"599520,351728462","147675,814176725",O,1,0
78383,1,126,321,501,501,321,5,5,01/01/2006,95199,-1,5,01/01/2006,DOPIGA,DOPIGA,?,"598199,332420137","148635,119288464",N,1,0

In [16]:
path4 = "E:/Study/stif_gtfs/routes.txt"
routes = pd.read_csv(path4,header = 0)
routes

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
0,254177100:100,848,100,100,NaN,3,NaN,000000,FFFFFF
1,287191100:191-100,822,191-100,Express 191-100,NaN,3,NaN,1AC7FF,000000
2,287094001:GOCparis,822,GO Cparis,GO C PARIS,NaN,3,NaN,000000,FFFFFF
3,057314100:100,95,100,Express 100 Les Mureaux St Quentin,NaN,3,NaN,000000,FFFFFF
4,057314143:ExpA14,95,Exp A14,Express A14 Verneuil,NaN,3,NaN,1AC7FF,000000
5,057314142:ExpA14,95,Exp A14,Express A14 Les Mureaux,NaN,3,NaN,1AC7FF,000000
6,116295008:FILEOFO,319,FILEO FO,Fileo Fosses (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
7,116295003:FILEOG,319,FILEO G,Fileo Goussainville (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
8,116277005:FILEOO,319,FILEO O,Fileo Othis (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
9,116295032:32,319,32,32,NaN,3,NaN,000000,FFFFFF
10,116193100:100C,914,100C,100,NaN,3,NaN,000000,FFFFFF
11,116195100:100P,758,100P,Express 100,NaN,3,NaN,000000,FFFFFF
12,116295027:27,319,27,27,NaN,3,NaN,000000,FFFFFF
13,116277010:FILEOV,319,FILEO V,Fileo Villeparisis (sur r√©servation),NaN,3,NaN,000000,FFFFFF
14,116295004:FILEOVB,319,FILEO VB,Fileo Villiers le Bel (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
15,116931007:FILEOVE,319,FILEO VE,Fileo Villepinte (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
16,116931002:FILEOT,319,FILEO T,Fileo Tremblay (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
17,116295001:FILEOS,319,FILEO S,Fileo Sarcelles (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
18,116931006:FILEOSL,319,FILEO SL,Fileo Sevran (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
19,116277009:FILEOSP,319,FILEO SP,Fileo Saint-Pathus (sur r√©servation),NaN,3,NaN,003BD1,FFFFFF
20,251195042:95-42,758,95-42,95-42,NaN,3,NaN,80E6BF,000000
21,251195043:95-43,758,95-43,95-43,NaN,3,NaN,A1B8CF,000000
22,251195041:95-41,758,95-41,95-41,NaN,3,NaN,006652,FFFFFF
23,251195004:95-04,758,95-04,95-04,NaN,3,NaN,1AC7FF,000000
24,251195011:95-11,758,95-11,95-11,NaN,3,NaN,BF008F,FFFFFF
...,...,...,...,...,...,...,...,...,...
1841,800:D:Bus,741,D,D,NaN,3,NaN,009149,FFFFFF
1842,800:C,741,C,C,NaN,2,NaN,E5C400,FFFFFF
1843,800:C:Bus,741,C,C,NaN,3,NaN,E5C400,FFFFFF
1844,810:B,741,B,B,NaN,2,NaN,1C83C2,FFFFFF
1845,800:E,741,E,E,NaN,2,NaN,CD659F,FFFFFF
1846,800:E:Bus,741,E,E,NaN,3,NaN,CD659F,FFFFFF
1847,800:T4,440,T4,T4,NaN,0,NaN,F1B400,FFFFFF
1848,800:T4:Bus,440,T4,T4,NaN,3,NaN,F1B400,FFFFFF
1849,800:T11,440,T11,T11 Express,NaN,0,NaN,E45E37,FFFFFF
1850,800:TER,743,TER,TER,NaN,2,NaN,000000,FFFFFF
1851,810:A,741,A,A,NaN,2,NaN,000000,FFFFFF
1852,810:A:Bus,741,A,A,NaN,3,NaN,000000,FFFFFF
1853,800:L,742,L,L,NaN,2,NaN,ADA6CE,FFFFFF
1854,800:L:Bus,742,L,L,NaN,3,NaN,ADA6CE,FFFFFF
1855,800:K,742,K,K,NaN,2,NaN,000000,FFFFFF
1856,800:J,742,J,J,NaN,2,NaN,C6CC00,FFFFFF
1857,800:J:Bus,742,J,J,NaN,3,NaN,C6CC00,FFFFFF
1858,800:N,742,N,N,NaN,2,NaN,000000,FFFFFF
1859,800:N:Bus,742,N,N,NaN,3,NaN,000000,FFFFFF
1860,800:U,742,U,U,NaN,2,NaN,DE4F75,FFFFFF
1861,800:U:Bus,742,U,U,NaN,3,NaN,DE4F75,FFFFFF
1862,800:R,742,R,R,NaN,2,NaN,000000,FFFFFF
1863,800:R:Bus,742,R,R,NaN,3,NaN,000000,FFFFFF
1864,800:P,742,P,P,NaN,2,NaN,000000,FFFFFF
1865,800:P:Bus,742,P,P,NaN,3,NaN,000000,FFFFFF

In [17]:
get_counts(routes['route_type'])

{0: 10, 1: 16, 2: 14, 3: 1823, 7: 3}

In [18]:
path_agency = "E:/Study/stif_gtfs/agency.txt"
agency = pd.read_csv(path_agency, header = 0)
agency

,agency_id,agency_name,agency_url,agency_timezone,agency_lang
0,848,Transdev Ile-de-France Lys,http://www.vianavigo.com,Europe/Paris,fr
1,822,Keolis Orly Rungis,http://www.vianavigo.com,Europe/Paris,fr
2,95,Express A14,http://www.vianavigo.com,Europe/Paris,fr
3,319,Fil√©o,http://www.vianavigo.com,Europe/Paris,fr
4,914,KMR,http://www.vianavigo.com,Europe/Paris,fr
5,758,Busval d'Oise,http://www.vianavigo.com,Europe/Paris,fr
6,584,TAM,http://www.vianavigo.com,Europe/Paris,fr
7,750,MAGICAL SHUTTLE,http://www.vianavigo.com,Europe/Paris,fr
8,302,Com'Bus,http://www.vianavigo.com,Europe/Paris,fr
9,303,Actip√¥les,http://www.vianavigo.com,Europe/Paris,fr
10,285,Ph√©bus,http://www.vianavigo.com,Europe/Paris,fr
11,782,Titus,http://www.vianavigo.com,Europe/Paris,fr
12,783,Aubergenville,http://www.vianavigo.com,Europe/Paris,fr
13,881,Paris-Saclay,http://www.vianavigo.com,Europe/Paris,fr
14,658,ADP,http://www.vianavigo.com,Europe/Paris,fr
15,441,Navette,http://www.vianavigo.com,Europe/Paris,fr
16,354,SNCF,http://www.vianavigo.com,Europe/Paris,fr
17,916,Seine-Saint-Denis,http://www.vianavigo.com,Europe/Paris,fr
18,426,TVS,http://www.vianavigo.com,Europe/Paris,fr
19,410,CARS PERRON,http://www.vianavigo.com,Europe/Paris,fr
20,35,CARS SOEUR,http://www.vianavigo.com,Europe/Paris,fr
21,33,Cars ROSE,http://www.vianavigo.com,Europe/Paris,fr
22,726,Bouff√©mont,http://www.vianavigo.com,Europe/Paris,fr
23,30,CARS MOREAU,http://www.vianavigo.com,Europe/Paris,fr
24,870,VIAMO-MELUN,http://www.vianavigo.com,Europe/Paris,fr
...,...,...,...,...,...
94,295,R'bus,http://www.vianavigo.com,Europe/Paris,fr
95,14,Bus en Seine,http://www.vianavigo.com,Europe/Paris,fr
96,132,Traverciel,http://www.vianavigo.com,Europe/Paris,fr
97,855,Scolaire Est Yvelines,http://www.vianavigo.com,Europe/Paris,fr
98,266,Entre Seine et For√™t,http://www.vianavigo.com,Europe/Paris,fr
99,661,Transdev Ile-de-France Montesson Les Rabaux,http://www.vianavigo.com,Europe/Paris,fr
100,330,Resalys,http://www.vianavigo.com,Europe/Paris,fr
101,896,LE BUS DIRECT,http://www.vianavigo.com,Europe/Paris,fr
102,412,Ulys,http://www.vianavigo.com,Europe/Paris,fr
103,639,AUTOCARS DOMINIQUE,http://www.vianavigo.com,Europe/Paris,fr
104,422,LOSAY VOYAGES,http://www.vianavigo.com,Europe/Paris,fr
105,930,Brie Bus,http://www.vianavigo.com,Europe/Paris,fr
106,929,Plateau de Brie,http://www.vianavigo.com,Europe/Paris,fr
107,127,Trans Val d'Oise,http://www.vianavigo.com,Europe/Paris,fr
108,471,TICE,http://www.vianavigo.com,Europe/Paris,fr
109,339,CIF,http://www.vianavigo.com,Europe/Paris,fr
110,557,Go√´lys,http://www.vianavigo.com,Europe/Paris,fr
111,15,Bus Haut Val d'Oise,http://www.vianavigo.com,Europe/Paris,fr
112,651,KVO,http://www.vianavigo.com,Europe/Paris,fr
113,829,Keolis Seine Val-De-Marne,http://www.vianavigo.com,Europe/Paris,fr
114,943,Trans'Essonne,http://www.vianavigo.com,Europe/Paris,fr
115,817,Seine Essonne Bus,http://www.vianavigo.com,Europe/Paris,fr
116,742,TRAIN,http://www.vianavigo.com,Europe/Paris,fr
117,741,RER,http://www.vianavigo.com,Europe/Paris,fr
118,743,TER,http://www.vianavigo.com,Europe/Paris,fr