In [1]:
import pandas as pd

In [29]:
entree = ['01 ', '011', '031', '041', '043', '051', '1', '11','11 ','17', '17 ', '31', '41', '43', '51' ]
sortie = ['02 ', '052', '2', '52']
entree_c = ['03 ', '056', '22', '22 ', '3', '42', '56']
sortie_c = ['04 ', '057', '4', '57'] 
columns = ['client_id','date',  'O', 'D', 'Ot', 'Dt','mode_TRNS', 'mode_RES' ,
           'O_station','D_station','ligne', 'unkonwn','O_zones','O_x','O_y','D_zones','D_x','D_y', 'O_mode', 'D_mode']

In [3]:
def get_counts(anything):
    counts = {}
    for a in anything:
        if a in counts:
            counts[a] = counts[a] + 1
        else:
            counts[a] = 1
    return counts

In [32]:
def  trip_prediction(data, n, index):
    i = 0
    transfer_id = 0
    trips = pd.DataFrame([], columns=columns)
    start = data.loc[index]     #start would be used in the final trip
    end = data.loc[index+n-1]
    while i+1 < n:
        first = data.loc[index+i]
        second = data.loc[index+i+1]
        first_location = arrets[(arrets['COD_TLB_ARRT_STTN'] == first['COD_TLB_ARRT_STTN'])
                                &(arrets['LIBL_LONG_ARRT_STTN'] == first['Lib_Arret'])]
        second_location = arrets[(arrets['COD_TLB_ARRT_STTN'] == second['COD_TLB_ARRT_STTN'])
                                &(arrets['LIBL_LONG_ARRT_STTN'] == second['Lib_Arret'])]
        if (len(first_location) == 0) or (len(second_location) == 0):
            return pd.DataFrame()
        first_zones, first_location_x, first_location_y = first_location.iloc[0][['ZONS_ARRT',
                                                                                  'COOR_X_PHSQ',
                                                                                  'COOR_Y_PHSQ']].get_values()
        second_zones, second_location_x, second_location_y = second_location.iloc[0][['ZONS_ARRT',
                                                                                      'COOR_X_PHSQ', 
                                                                                      'COOR_Y_PHSQ']].get_values()       
        first_data = [first['NUMR_CART'], first['JOUR_EXPL_VALD'], 
                      first['Lib_Arret'], second['Lib_Arret'], first['HEUR_VALD'], second['HEUR_VALD'], first['COD_STF_TRNS'],
                      first['COD_STF_RES'],first['COD_TLB_ARRT_STTN'],second['COD_TLB_ARRT_STTN'],first['COD_STF_LIGN'], 'd', first_zones,
                      first_location_x, first_location_y, second_zones, 
                      second_location_x, second_location_y, first['COD_MOD_VALD'], second['COD_MOD_VALD']]
        trips.loc[transfer_id] = first_data
        if second['COD_NATR_VALD'] in sortie:
            trips.loc[transfer_id, 'unkonwn'] = 'no'
            transfer_id = transfer_id + 1 
            i = i + 2
        else:
            transfer_id = transfer_id + 1
            i = i + 1
    if (i+1) == n:  # which means the last trip is a 'E'   
        start_location =  arrets[(arrets['COD_TLB_ARRT_STTN'] == start['COD_TLB_ARRT_STTN'])
                                 &(arrets['LIBL_LONG_ARRT_STTN'] == start['Lib_Arret'])]
        end_location = arrets[(arrets['COD_TLB_ARRT_STTN'] == end['COD_TLB_ARRT_STTN'])
                              &(arrets['LIBL_LONG_ARRT_STTN'] == end['Lib_Arret'])]
        if (len(start_location)==0) or (len(end_location)==0):
            return pd.DataFrame()
        start_zones, start_location_x, start_location_y = start_location.iloc[0][['ZONS_ARRT',
                                                                                  'COOR_X_PHSQ',
                                                                                  'COOR_Y_PHSQ']].get_values()
        
        end_zones, end_location_x, end_location_y = end_location.iloc[0][['ZONS_ARRT',
                                                                          'COOR_X_PHSQ',
                                                                          'COOR_Y_PHSQ']].get_values()
        last_data = [end['NUMR_CART'], end['JOUR_EXPL_VALD'], 
                     end['Lib_Arret'], start['Lib_Arret'], end['HEUR_VALD'], '', end['COD_STF_TRNS'], 
                     end['COD_STF_RES'], end['COD_TLB_ARRT_STTN'],start['COD_TLB_ARRT_STTN'], 
                     end['COD_STF_LIGN'], 'dh', end_zones,end_location_x,end_location_y, 
                    start_zones,start_location_x,start_location_y, end['COD_MOD_VALD'], start['COD_MOD_VALD']]
        trips.loc[transfer_id] = last_data
    return trips

In [14]:
def  output(data, n):
    trips = pd.DataFrame()
    for index in range(int(len(data)/n)):
        a= trip_prediction(data, n, index*n)
        trips =  trips.append(a, ignore_index = True)
    return trips

In [6]:
path_3 =  'F:/Stage/data/AFC/counts/counts_3'
path_1 = 'F:/Stage/data/AFC/counts/counts_1'
path_arret = "F:/Stage/data/AFC/DM arret.txt"
path_2 = 'F:/Stage/data/AFC/counts/counts_2'
path_4 =  'F:/Stage/data/AFC/counts/counts_4'
path_5 =  'F:/Stage/data/AFC/counts/counts_5'
path_6 =  'F:/Stage/data/AFC/counts/counts_6'
path_7 =  'F:/Stage/data/AFC/counts/counts_7'

In [7]:
data_3 = pd.read_csv(path_3, delimiter="\t", header = 0, encoding="latin-1")
data_3['COD_NATR_VALD'] = data_3['COD_NATR_VALD'].astype('str')
data_3['HEUR_VALD'] = pd.to_timedelta(data_3['HEUR_VALD'])
data_3_sort = data_3.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_3_sort = data_3_sort.reset_index(drop = True)

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
data_4 = pd.read_csv(path_4, delimiter="\t", header = 0, encoding="latin-1")
data_4['COD_NATR_VALD'] = data_4['COD_NATR_VALD'].astype('str')
data_4['HEUR_VALD'] = pd.to_timedelta(data_4['HEUR_VALD'])
data_4_sort = data_4.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_4_sort = data_4_sort.reset_index(drop = True)

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
data_5 = pd.read_csv(path_5, delimiter="\t", header = 0, encoding="latin-1")
data_5['COD_NATR_VALD'] = data_5['COD_NATR_VALD'].astype('str')
data_5['HEUR_VALD'] = pd.to_timedelta(data_5['HEUR_VALD'])
data_5_sort = data_5.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_5_sort = data_5_sort.reset_index(drop = True)

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
data_7 = pd.read_csv(path_7, delimiter="\t", header = 0, encoding="latin-1")
data_7['COD_NATR_VALD'] = data_7['COD_NATR_VALD'].astype('str')
data_7['HEUR_VALD'] = pd.to_timedelta(data_7['HEUR_VALD'])
data_7_sort = data_7.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_7_sort = data_7_sort.reset_index(drop = True)

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
data_6 = pd.read_csv(path_6, delimiter="\t", header = 0, encoding="latin-1")
data_6['COD_NATR_VALD'] = data_6['COD_NATR_VALD'].astype('str')
data_6['HEUR_VALD'] = pd.to_timedelta(data_6['HEUR_VALD'])
data_6_sort = data_6.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_6_sort = data_6_sort.reset_index(drop = True)

In [4]:
data_2 = pd.read_csv(path_2, delimiter="\t", header = 0, encoding="latin-1")
data_2['COD_NATR_VALD'] = data_2['COD_NATR_VALD'].astype('str')
data_2['HEUR_VALD'] = pd.to_timedelta(data_2['HEUR_VALD'])
data_2_sort = data_2.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_2_sort = data_2_sort.reset_index(drop = True)

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
data_2_sort[data_2_sort['NUMR_CART'] == '99988615879853555405']

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
168,12475602,99988615879853555405,14/03/2017,06:10:33,SAINT-DENIS,2,002,271015,20500505,1,1,800,853,ND
169,12475690,99988615879853555405,14/03/2017,16:11:09,SAINT-DENIS,2,002,271015,14500505,2,1,800,853,ND

In [6]:
data_2_sort[data_2_sort['NUMR_CART'] == '99985864111412513744']

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
222,10046219,99985864111412513744,14/03/2017,08:23:01,LA DEFENSE-GRANDE ARCHE,1,801,0030050170401,114,52,1,810,801,ND
223,10046131,99985864111412513744,14/03/2017,14:51:21,LA DEFENSE-GRANDE ARCHE,1,801,0030050170401,201,51,1,810,801,ND

In [9]:
data_2_sort[data_2_sort['NUMR_CART'] == '99965752444344107009']

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
512,75065,99965752444344107009,14/03/2017,07:55:13,POISSY,1,801,386573,12321002,1,1,810,801,ND
513,75153,99965752444344107009,14/03/2017,18:33:19,POISSY,1,801,386573,15321002,2,1,810,801,ND

In [25]:
get_counts(data_3_sort['COD_MOD_VALD'])

{-1: 6, 1: 404013, 2: 393623, 3: 540069, 4: 53865, 6: 1309}

In [10]:
arrets = pd.read_csv(path_arret, delimiter="\t", header= 0, encoding="latin-1")
arrets = arrets[arrets.ZONS_ARRT != 'ND ']
arrets = arrets[arrets.COOR_X_PHSQ != '-1']
arrets = arrets[arrets.COOR_X_PHSQ != '?']
arrets['COOR_X_PHSQ'] = arrets['COOR_X_PHSQ'].apply(lambda x: float((x.split(',')[0])))
arrets['COOR_Y_PHSQ'] = arrets['COOR_Y_PHSQ'].apply(lambda x: float((x.split(',')[0])))

In [8]:
select_data = data_3_sort.iloc[:100]
select_data

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
0,6289284,99999942845366768893,14/03/2017,10:57:31,PYRENEES,3,001,0030030241400,101,31,3,100,110,ND
1,6289196,99999942845366768893,14/03/2017,17:30:51,SAINT-GERMAIN-DES-PRES,3,001,0030030021500,232,31,3,100,110,ND
2,1723316,99999942845366768893,14/03/2017,18:50:29,CHATELET,3,001,0030030010800,401,31,3,100,110,ND
3,7153827,99999577198461515588,14/03/2017,08:00:58,HOTEL DE VILLE DE FONTENAY,3,001,0030010124016,2125,11,2,100,100,124
4,7153915,99999577198461515588,14/03/2017,08:20:46,VAL DE FONTENAY RER,3,001,0030010118015,6803,11,2,100,100,118
5,11376859,99999577198461515588,14/03/2017,19:25:28,VAL DE FONTENAY RER,3,001,0030010124022,9042,11,2,100,100,124
6,354119,99999492695837542235,14/03/2017,08:02:30,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,3,001,0030010151012,611,11,2,100,100,151
7,354031,99999492695837542235,14/03/2017,10:11:44,PLACE DU 19 MARS 1962,3,001,0030010151034,11948,11,2,100,100,151
8,354207,99999492695837542235,14/03/2017,12:29:00,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,3,001,0030010151012,1753,11,2,100,100,151
9,6550859,99998853895565292735,14/03/2017,07:56:20,MAIRIE DE ROMAINVILLE,3,001,0030010105047,983,11,2,100,100,105
10,6550947,99998853895565292735,14/03/2017,08:10:03,MAIRIE DES LILAS,3,001,0030030230300,104,31,3,100,110,ND
11,6551035,99998853895565292735,14/03/2017,17:09:35,PYRENEES,3,001,0030030241400,103,31,3,100,110,ND
12,11137569,99998786964033820793,14/03/2017,08:29:10,RICHELIEU-DROUOT,3,001,0030030110700,401,31,3,100,110,ND
13,2536801,99998786964033820793,14/03/2017,15:53:07,LA MUETTE,3,001,0030030171100,102,31,3,100,110,ND
14,2536889,99998786964033820793,14/03/2017,20:12:29,RUE DU BAC,3,001,0030030021000,103,31,3,100,110,ND
15,12431870,99998614886067744792,14/03/2017,09:03:24,GARE DE LYON,3,001,0030030090800,103,031,3,100,110,ND
16,8265510,99998614886067744792,14/03/2017,18:21:02,LOUIS BLANC,3,001,0030030221000,102,31,3,100,110,ND
17,3943302,99998614886067744792,14/03/2017,19:30:47,PORTE DE LA VILLETTE,3,001,0030030030400,105,31,3,100,110,ND
18,7265193,99997990729919865119,14/03/2017,09:13:04,MARCADET-POISSONNIERS,3,001,0030030200900,102,31,3,100,110,ND
19,7265105,99997990729919865119,14/03/2017,19:43:54,MAIRIE DE CLICHY,3,001,0030030190100,102,31,3,100,110,ND
20,2810545,99997990729919865119,14/03/2017,19:59:14,BROCHANT - CARDINET,3,001,0030010031034,14809,11,2,100,100,31
21,10789855,99997955226236728234,14/03/2017,18:07:30,CERGY-SAINT-CHRISTOPHE,1,801,382499,22331201,1,1,810,801,ND
22,10789679,99997955226236728234,14/03/2017,18:35:00,Gare d'Houilles Carrières sur Seine,119,248,19079,3575,11,2,19,248,19
23,10789767,99997955226236728234,14/03/2017,18:41:19,HOUILLES-CARRIERES-SUR-SEINE,1,801,386409,30320704,2,1,810,801,ND
24,7381774,99997804846299180110,14/03/2017,09:03:11,LES VALLEES,2,002,386300,3320505,1,1,800,854,ND
25,7381862,99997804846299180110,14/03/2017,09:14:38,NANTERRE-VILLE,1,801,0030050170503,208,52,1,810,801,ND
26,7381950,99997804846299180110,14/03/2017,18:50:13,NANTERRE-VILLE,1,801,0030050170503,201,51,1,810,801,ND
27,5467559,99997800772878601333,14/03/2017,13:07:09,GUY MOQUET,3,001,0030030301200,101,31,3,100,110,ND
28,770559,99997800772878601333,14/03/2017,16:37:29,CHATELET,3,001,0030030010800,103,31,3,100,110,ND
29,9660055,99997800772878601333,14/03/2017,18:07:47,JOURDAIN,3,001,0030030231400,103,31,3,100,110,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,7365967,99994930696312615749,14/03/2017,09:52:55,JUSSIEU,3,001,0030030120700,103,31,3,100,110,ND
71,7366055,99994930696312615749,14/03/2017,16:50:48,MAUBERT-MUTUALITE,3,001,0030030010600,102,31,3,100,110,ND
72,7769178,99994701783103665215,14/03/2017,08:37:34,DUROC,3,001,0030030020700,103,31,3,100,110,ND
73,11940290,99994701783103665215,14/03/2017,08:58:38,NATIONALE,3,001,0030010027059,9106,11,2,100,100,27
74,7769266,99994701783103665215,14/03/2017,15:11:00,NATIONALE,3,001,0030030141100,102,31,3,100,110,ND
75,10993274,99994623185800459079,14/03/2017,07:24:00,René Renault,189,218,182,0,17,2,350,350,31
76,6843282,99994623185800459079,14/03/2017,14:58:00,Domaine de la Vallée,189,218,211,0,17,2,350,350,12
77,6843194,99994623185800459079,14/03/2017,15:28:00,Division Leclerc,189,218,368,0,17,2,350,350,31
78,9055534,99994503496590488527,14/03/2017,14:19:10,Inconnu,3,001,*100,17053,011,2,100,100,86
79,13974,99994503496590488527,14/03/2017,14:29:12,LEDRU-ROLLIN,3,1,0030030121500,103,31,3,100,110,ND
80,4836198,99994503496590488527,14/03/2017,17:19:13,SAINT-SULPICE,3,001,0030030021200,201,31,3,100,110,ND
81,5899586,99994453678664675520,14/03/2017,15:11:50,CHARONNE,3,001,0030030240200,102,31,3,100,110,ND
82,10091554,99994453678664675520,14/03/2017,15:56:28,CITE,3,001,0030030011400,102,31,3,100,110,ND
83,5899674,99994453678664675520,14/03/2017,17:53:57,STRASBOURG-SAINT-DENIS,3,001,0030030111000,201,31,3,100,110,ND
84,2966404,99994402105613089205,14/03/2017,10:02:14,MARCEL SEMBAT,3,1,0030030280800,104,31,3,100,110,ND
85,2966492,99994402105613089205,14/03/2017,10:08:39,BOULAINVILLIERS,2,2,543181,32550004,3,1,800,803,ND
86,2966580,99994402105613089205,14/03/2017,14:52:08,BOULAINVILLIERS,2,2,543181,39550004,4,3,800,803,ND
87,621678,99994342111011611094,14/03/2017,07:05:46,NOISY-LE-SEC RER,3,1,0030010143134,180,11,2,100,100,143
88,9508622,99994342111011611094,14/03/2017,10:01:10,CITE DU MOULIN,3,001,0030010249042,16714,11,2,100,100,249
89,5310230,99994342111011611094,14/03/2017,16:15:26,JEAN JAURES - DIVISION LECLERC,3,001,0030010143104,16294,11,2,100,100,143
90,5705530,99994221414895854222,14/03/2017,16:50:03,ANTONY,1,802,0030050180501,208,51,1,810,802,ND
91,1071890,99994221414895854222,14/03/2017,17:23:25,CHATELET-LES HALLES,1,801,0030050011000,208,52,1,810,801,ND
92,5705442,99994221414895854222,14/03/2017,17:24:26,LES HALLES,3,001,0030030010900,106,31,3,100,110,ND
93,7646207,99994213907684520684,14/03/2017,10:14:22,COURONNES,3,001,0030030241300,102,31,3,100,110,ND
94,11810631,99994213907684520684,14/03/2017,13:58:22,BROCHANT,3,001,0030030300800,102,31,3,100,110,ND
95,3268295,99994213907684520684,14/03/2017,19:51:51,LES AGNETTES-ASNIERES-GENNEVILLIERS,3,001,0030030190300,104,31,3,100,110,ND
96,11227223,99993895346189045242,14/03/2017,08:42:10,ROSA PARKS,2,002,654798,28200107,1,1,800,805,ND
97,2684095,99993895346189045242,14/03/2017,08:55:30,HAUSSMANN-SAINT-LAZARE,2,002,281899,15500003,2,1,800,805,ND
98,2684183,99993895346189045242,14/03/2017,09:00:08,SAINT-LAZARE,3,001,0030030060800,204,31,3,100,110,ND
99,11071532,99993844160407781116,14/03/2017,11:30:48,VILLENEUVE-SAINT-GEORGES,2,002,681825,12400801,1,1,800,804,ND

18268.0

In [33]:
output_file = output(select_data, 3)

In [34]:
output_file

,client_id,date,O,D,Ot,Dt,mode_TRNS,mode_RES,O_station,D_station,ligne,unkonwn,O_zones,O_x,O_y,D_zones,D_x,D_y,O_mode,D_mode
0,99999942845366768893,14/03/2017,PYRENEES,SAINT-GERMAIN-DES-PRES,10:57:31,0 days 17:30:51,100,110,0030030241400,0030030021500,ND,d,1,603578.0,130382.0,1,599798.0,128139.0,3,3
1,99999942845366768893,14/03/2017,SAINT-GERMAIN-DES-PRES,CHATELET,17:30:51,0 days 18:50:29,100,110,0030030021500,0030030010800,ND,d,1,599798.0,128139.0,1,600864.0,128566.0,3,3
2,99999942845366768893,14/03/2017,CHATELET,PYRENEES,18:50:29,,100,110,0030030010800,0030030241400,ND,dh,1,600864.0,128566.0,1,603578.0,130382.0,3,3
3,99999577198461515588,14/03/2017,HOTEL DE VILLE DE FONTENAY,VAL DE FONTENAY RER,08:00:58,0 days 08:20:46,100,100,0030010124016,0030010118015,124,d,3,610411.0,127523.0,3,611092.0,128164.0,2,2
4,99999577198461515588,14/03/2017,VAL DE FONTENAY RER,VAL DE FONTENAY RER,08:20:46,0 days 19:25:28,100,100,0030010118015,0030010124022,118,d,3,611092.0,128164.0,3,611078.0,128101.0,2,2
5,99999577198461515588,14/03/2017,VAL DE FONTENAY RER,HOTEL DE VILLE DE FONTENAY,19:25:28,,100,100,0030010124022,0030010124016,124,dh,3,611078.0,128101.0,3,610411.0,127523.0,2,2
6,99999492695837542235,14/03/2017,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,PLACE DU 19 MARS 1962,08:02:30,0 days 10:11:44,100,100,0030010151012,0030010151034,151,d,3,607422.0,134759.0,3,608448.0,135511.0,2,2
7,99999492695837542235,14/03/2017,PLACE DU 19 MARS 1962,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,10:11:44,0 days 12:29:00,100,100,0030010151034,0030010151012,151,d,3,608448.0,135511.0,3,607422.0,134759.0,2,2
8,99999492695837542235,14/03/2017,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,12:29:00,,100,100,0030010151012,0030010151012,151,dh,3,607422.0,134759.0,3,607422.0,134759.0,2,2
9,99998853895565292735,14/03/2017,MAIRIE DE ROMAINVILLE,MAIRIE DES LILAS,07:56:20,0 days 08:10:03,100,100,0030010105047,0030030230300,105,d,3,607221.0,131628.0,2,605864.0,131038.0,2,3
10,99998853895565292735,14/03/2017,MAIRIE DES LILAS,PYRENEES,08:10:03,0 days 17:09:35,100,110,0030030230300,0030030241400,ND,d,2,605864.0,131038.0,1,603578.0,130382.0,3,3
11,99998853895565292735,14/03/2017,PYRENEES,MAIRIE DE ROMAINVILLE,17:09:35,,100,110,0030030241400,0030010105047,ND,dh,1,603578.0,130382.0,3,607221.0,131628.0,3,2
12,99998786964033820793,14/03/2017,RICHELIEU-DROUOT,LA MUETTE,08:29:10,0 days 15:53:07,100,110,0030030110700,0030030171100,ND,d,1,600183.0,130148.0,1,595423.0,128622.0,3,3
13,99998786964033820793,14/03/2017,LA MUETTE,RUE DU BAC,15:53:07,0 days 20:12:29,100,110,0030030171100,0030030021000,ND,d,1,595423.0,128622.0,1,599206.0,128343.0,3,3
14,99998786964033820793,14/03/2017,RUE DU BAC,RICHELIEU-DROUOT,20:12:29,,100,110,0030030021000,0030030110700,ND,dh,1,599206.0,128343.0,1,600183.0,130148.0,3,3
15,99998614886067744792,14/03/2017,GARE DE LYON,LOUIS BLANC,09:03:24,0 days 18:21:02,100,110,0030030090800,0030030221000,ND,d,1,602678.0,127057.0,1,602128.0,131205.0,3,3
16,99998614886067744792,14/03/2017,LOUIS BLANC,PORTE DE LA VILLETTE,18:21:02,0 days 19:30:47,100,110,0030030221000,0030030030400,ND,d,1,602128.0,131205.0,1,603591.0,132997.0,3,3
17,99998614886067744792,14/03/2017,PORTE DE LA VILLETTE,GARE DE LYON,19:30:47,,100,110,0030030030400,0030030090800,ND,dh,1,603591.0,132997.0,1,602678.0,127057.0,3,3
18,99997990729919865119,14/03/2017,MARCADET-POISSONNIERS,MAIRIE DE CLICHY,09:13:04,0 days 19:43:54,100,110,0030030200900,0030030190100,ND,d,1,600974.0,132337.0,2,597756.0,133656.0,3,3
19,99997990729919865119,14/03/2017,MAIRIE DE CLICHY,BROCHANT - CARDINET,19:43:54,0 days 19:59:14,100,110,0030030190100,0030010031034,ND,d,2,597756.0,133656.0,1,598662.0,132308.0,3,2
20,99997990729919865119,14/03/2017,BROCHANT - CARDINET,MARCADET-POISSONNIERS,19:59:14,,100,100,0030010031034,0030030200900,31,dh,1,598662.0,132308.0,1,600974.0,132337.0,2,3
21,99997955226236728234,14/03/2017,CERGY-SAINT-CHRISTOPHE,Gare d'Houilles Carrières sur Seine,18:07:30,0 days 18:35:00,810,801,382499,19079,ND,d,5,577909.0,149971.0,4,588956.0,135461.0,1,2
22,99997955226236728234,14/03/2017,Gare d'Houilles Carrières sur Seine,HOUILLES-CARRIERES-SUR-SEINE,18:35:00,0 days 18:41:19,19,248,19079,386409,19,no,4,588956.0,135461.0,4,588921.0,135563.0,2,1
23,99997804846299180110,14/03/2017,LES VALLEES,NANTERRE-VILLE,09:03:11,0 days 09:14:38,800,854,386300,0030050170503,ND,no,3,594195.0,134805.0,3,589650.0,132753.0,1,1
24,99997804846299180110,14/03/2017,NANTERRE-VILLE,LES VALLEES,18:50:13,,810,801,0030050170503,386300,ND,dh,3,589650.0,132753.0,3,594195.0,134805.0,1,1
25,99997800772878601333,14/03/2017,GUY MOQUET,CHATELET,13:07:09,0 days 16:37:29,100,110,0030030301200,0030030010800,ND,d,1,599333.0,132488.0,1,600864.0,128566.0,3,3
26,99997800772878601333,14/03/2017,CHATELET,JOURDAIN,16:37:29,0 days 18:07:47,100,110,0030030010800,0030030231400,ND,d,1,600864.0,128566.0,1,603879.0,130519.0,3,3
27,99997800772878601333,14/03/2017,JOURDAIN,GUY MOQUET,18:07:47,,100,110,0030030231400,0030030301200,ND,dh,1,603879.0,130519.0,1,599333.0,132488.0,3,3
28,99997570798660882124,14/03/2017,Résidence La Forêt,Gare Rive Droite,09:46:00,0 days 10:47:00,56,356,226,580,5,d,4,586342.0,123875.0,4,585124.0,123282.0,2,2
29,99997570798660882124,14/03/2017,Gare Rive Droite,Pershing,10:47:00,0 days 10:48:00,56,356,580,165,5,d,4,585124.0,123282.0,4,586315.0,124232.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,99995587679220601600,14/03/2017,DAUMESNIL,CHARENTON-ECOLES,14:32:53,,100,110,0030030131100,0030030251300,ND,dh,1,604343.0,126565.0,2,605669.0,124570.0,3,3
56,99995248842220264654,14/03/2017,AEROPORT CHARLES DE GAULLE 2-TGV,MARAICHERS,16:08:42,0 days 20:05:08,810,802,271494,0030030050400,ND,d,5,617123.0,144953.0,1,605104.0,128031.0,1,3
57,99995248842220264654,14/03/2017,MARAICHERS,SAINT-MICHEL,20:05:08,0 days 21:47:59,100,110,0030030050400,0030030010100,ND,d,1,605104.0,128031.0,1,600496.0,128078.0,3,3
58,99995248842220264654,14/03/2017,SAINT-MICHEL,AEROPORT CHARLES DE GAULLE 2-TGV,21:47:59,,100,110,0030030010100,271494,ND,dh,1,600496.0,128078.0,5,617123.0,144953.0,3,1
59,99994954377616055349,14/03/2017,JEAN MOULIN,HOTEL DE VILLE DE CRETEIL,10:17:22,0 days 11:20:54,100,100,0030010117024,0030010317001,117,d,3,612169.0,121909.0,3,608730.0,119713.0,2,2
60,99994954377616055349,14/03/2017,HOTEL DE VILLE DE CRETEIL,BEAUJEU,11:20:54,0 days 11:55:08,100,100,0030010317001,0030010112019,317,d,3,608730.0,119713.0,3,610490.0,121971.0,2,2
61,99994954377616055349,14/03/2017,BEAUJEU,JEAN MOULIN,11:55:08,,100,100,0030010112019,0030010117024,112,dh,3,610490.0,121971.0,3,612169.0,121909.0,2,2
62,99994930696312615749,14/03/2017,NATION - FAUBOURG SAINT-ANTOINE,JUSSIEU,09:28:22,0 days 09:52:55,100,100,0030010086011,0030030120700,86,d,1,604267.0,127580.0,1,601349.0,127298.0,2,3
63,99994930696312615749,14/03/2017,JUSSIEU,MAUBERT-MUTUALITE,09:52:55,0 days 16:50:48,100,110,0030030120700,0030030010600,ND,d,1,601349.0,127298.0,1,600846.0,127740.0,3,3
64,99994930696312615749,14/03/2017,MAUBERT-MUTUALITE,NATION - FAUBOURG SAINT-ANTOINE,16:50:48,,100,110,0030030010600,0030010086011,ND,dh,1,600846.0,127740.0,1,604267.0,127580.0,3,2
65,99994701783103665215,14/03/2017,DUROC,NATIONALE,08:37:34,0 days 08:58:38,100,110,0030030020700,0030010027059,ND,d,1,598567.0,127391.0,1,601913.0,125812.0,3,2
66,99994701783103665215,14/03/2017,NATIONALE,NATIONALE,08:58:38,0 days 15:11:00,100,100,0030010027059,0030030141100,27,d,1,601913.0,125812.0,1,601933.0,125860.0,2,3
67,99994701783103665215,14/03/2017,NATIONALE,DUROC,15:11:00,,100,110,0030030141100,0030030020700,ND,dh,1,601933.0,125860.0,1,598567.0,127391.0,3,3
68,99994623185800459079,14/03/2017,René Renault,Domaine de la Vallée,07:24:00,0 days 14:58:00,350,350,182,211,31,d,6,550774.0,142576.0,6,554749.0,141281.0,2,2
69,99994623185800459079,14/03/2017,Domaine de la Vallée,Division Leclerc,14:58:00,0 days 15:28:00,350,350,211,368,12,d,6,554749.0,141281.0,6,554162.0,143406.0,2,2
70,99994623185800459079,14/03/2017,Division Leclerc,René Renault,15:28:00,,350,350,368,182,31,dh,6,554162.0,143406.0,6,550774.0,142576.0,2,2
71,99994453678664675520,14/03/2017,CHARONNE,CITE,15:11:50,0 days 15:56:28,100,110,0030030240200,0030030011400,ND,d,1,603598.0,128236.0,1,600792.0,128275.0,3,3
72,99994453678664675520,14/03/2017,CITE,STRASBOURG-SAINT-DENIS,15:56:28,0 days 17:53:57,100,110,0030030011400,0030030111000,ND,d,1,600792.0,128275.0,1,601310.0,129893.0,3,3
73,99994453678664675520,14/03/2017,STRASBOURG-SAINT-DENIS,CHARONNE,17:53:57,,100,110,0030030111000,0030030240200,ND,dh,1,601310.0,129893.0,1,603598.0,128236.0,3,3
74,99994402105613089205,14/03/2017,MARCEL SEMBAT,BOULAINVILLIERS,10:02:14,0 days 10:08:39,100,110,0030030280800,543181,ND,d,2,593196.0,125918.0,1,595497.0,128454.0,3,1
75,99994402105613089205,14/03/2017,BOULAINVILLIERS,BOULAINVILLIERS,10:08:39,0 days 14:52:08,800,803,543181,543181,ND,d,1,595497.0,128454.0,1,595497.0,128454.0,1,3
76,99994402105613089205,14/03/2017,BOULAINVILLIERS,MARCEL SEMBAT,14:52:08,,800,803,543181,0030030280800,ND,dh,1,595497.0,128454.0,2,593196.0,125918.0,3,3
77,99994342111011611094,14/03/2017,NOISY-LE-SEC RER,CITE DU MOULIN,07:05:46,0 days 10:01:10,100,100,0030010143134,0030010249042,143,d,3,609132.0,132852.0,3,605633.0,139509.0,2,2
78,99994342111011611094,14/03/2017,CITE DU MOULIN,JEAN JAURES - DIVISION LECLERC,10:01:10,0 days 16:15:26,100,100,0030010249042,0030010143104,249,d,3,605633.0,139509.0,3,606442.0,136940.0,2,2
79,99994342111011611094,14/03/2017,JEAN JAURES - DIVISION LECLERC,NOISY-LE-SEC RER,16:15:26,,100,100,0030010143104,0030010143134,143,dh,3,606442.0,136940.0,3,609132.0,132852.0,2,2
80,99994221414895854222,14/03/2017,ANTONY,CHATELET-LES HALLES,16:50:03,0 days 17:23:25,810,802,0030050180501,0030050011000,ND,no,3,597386.0,117156.0,1,600769.0,129040.0,1,1
81,99994221414895854222,14/03/2017,LES HALLES,ANTONY,17:24:26,,100,110,0030030010900,0030050180501,ND,dh,1,600671.0,129095.0,3,597386.0,117156.0,3,1
82,99994213907684520684,14/03/2017,COURONNES,BROCHANT,10:14:22,0 days 13:58:22,100,110,0030030241300,0030030300800,ND,d,1,603229.0,129849.0,1,598801.0,132239.0,3,3
83,99994213907684520684,14/03/2017,BROCHANT,LES AGNETTES-ASNIERES-GENNEVILLIERS,13:58:22,0 days 19:51:51,100,110,0030030300800,0030030190300,ND,d,1,598801.0,132239.0,3,596318.0,135856.0,3,3
84,99994213907684520684,14/03/2017,LES AGNETTES-ASNIERES-GENNEVILLIERS,COURONNES,19:51:51,,100,110,0030030190300,0030030241300,ND,dh,3,596318.0,135856.0,1,603229.0,129849.0,3,3

In [13]:
output_path = 'E:/Study/data/7_0.csv'
output_file.to_csv(output_path, header=True,sep="\t", encoding='latin-1')