In [4]:
import pandas as pd

In [32]:
entree = ['01 ', '011', '031', '041', '043', '051', '1', '11','11 ','17', '17 ', '31', '41', '43', '51' ]
sortie = ['02 ', '052', '2', '52']
entree_c = ['03 ', '056', '22', '22 ', '3', '42', '56']
sortie_c = ['04 ', '057', '4', '57'] 
columns = ['trip_id', 'client_id','date',  'O', 'D', 'Ot', 'Dt','mode', 
           'O_station','D_station','ligne', 'unkonwn','O_zones','O_x','O_y','D_zones','D_x','D_y']
columns_n = ['trip_id', 'client_id','date',  'O', 'D', 'Ot', 'Dt','mode', 
             'O_station','D_station','ligne', 'unkonwn','O_mode','D_mode']
T = 7200

In [11]:
def get_counts(anything):
    counts = {}
    for a in anything:
        if a in counts:
            counts[a] = counts[a] + 1
        else:
            counts[a] = 1
    return counts

In [6]:
def  trip_prediction(data, n, index,trip_id):
    i = 0
    transfer_id = 0
    trips = pd.DataFrame([], columns=columns)
    start = data.loc[index]     #start would be used in the final trip
    end = data.loc[index+n-1]
    trip_start_time = start['HEUR_VALD']   
    while i+1 < n:
        first = data.loc[index+i]
        second = data.loc[index+i+1]
        first_location = arrets[(arrets['COD_TLB_ARRT_STTN'] == first['COD_TLB_ARRT_STTN'])
                                &(arrets['LIBL_LONG_ARRT_STTN'] == first['Lib_Arret'])]
        second_location = arrets[(arrets['COD_TLB_ARRT_STTN'] == second['COD_TLB_ARRT_STTN'])
                                &(arrets['LIBL_LONG_ARRT_STTN'] == second['Lib_Arret'])]
        if (len(first_location) == 0) or (len(second_location) == 0):
            return pd.DataFrame(), trip_id
        first_zones, first_location_x, first_location_y = first_location.iloc[0][['ZONS_ARRT',
                                                                                  'COOR_X_PHSQ',
                                                                                  'COOR_Y_PHSQ']].get_values()
        second_zones, second_location_x, second_location_y = second_location.iloc[0][['ZONS_ARRT',
                                                                                      'COOR_X_PHSQ', 
                                                                                      'COOR_Y_PHSQ']].get_values()
        
        first_data = [trip_id, first['NUMR_CART'], first['JOUR_EXPL_VALD'], 
                      first['Lib_Arret'], second['Lib_Arret'], first['HEUR_VALD'], second['HEUR_VALD'], first['COD_TLB_RES'], 
                      first['COD_TLB_ARRT_STTN'],second['COD_TLB_ARRT_STTN'],first['COD_STF_LIGN'], 'd', first_zones,
                     first_location_x, first_location_y, second_zones, second_location_x, second_location_y]
        trips.loc[transfer_id] = first_data
        if second['COD_NATR_VALD'] in sortie:
            trips.loc[transfer_id, 'unkonwn'] = 'no'
            transfer_id = transfer_id + 1 
            i = i + 2
        else:
            trips.loc[transfer_id, 'unkonwn'] = 'd'
            transfer_id = transfer_id + 1
            i = i + 1
            if (second['HEUR_VALD'] - trip_start_time).seconds > T:
                trip_start_time = second['HEUR_VALD']
                trip_id = trip_id + 1
    if (i+1) == n:  # which means the last trip is a 'E'
        if (end['HEUR_VALD'] -  trip_start_time).seconds > T:
            trip_id = trip_id + 1
        
        start_location =  arrets[(arrets['COD_TLB_ARRT_STTN'] == start['COD_TLB_ARRT_STTN'])
                                 &(arrets['LIBL_LONG_ARRT_STTN'] == start['Lib_Arret'])]
        end_location = arrets[(arrets['COD_TLB_ARRT_STTN'] == end['COD_TLB_ARRT_STTN'])
                              &(arrets['LIBL_LONG_ARRT_STTN'] == end['Lib_Arret'])]
        if (len(start_location)==0) or (len(end_location)==0):
            return pd.DataFrame(),trip_id
        start_zones, start_location_x, start_location_y = start_location.iloc[0][['ZONS_ARRT',
                                                                                  'COOR_X_PHSQ',
                                                                                  'COOR_Y_PHSQ']].get_values()
        
        end_zones, end_location_x, end_location_y = end_location.iloc[0][['ZONS_ARRT',
                                                                          'COOR_X_PHSQ',
                                                                          'COOR_Y_PHSQ']].get_values()
        last_data = [trip_id, end['NUMR_CART'], end['JOUR_EXPL_VALD'], 
                     end['Lib_Arret'], start['Lib_Arret'], end['HEUR_VALD'], '', 
                     end['COD_TLB_RES'], end['COD_TLB_ARRT_STTN'],start['COD_TLB_ARRT_STTN'], 
                     end['COD_STF_LIGN'], 'd', end_zones,end_location_x,end_location_y, 
                    start_zones,start_location_x,start_location_y]
        trips.loc[transfer_id] = last_data
        trips.loc[transfer_id, 'unkonwn'] = 'dh'
        if (end['HEUR_VALD'] - start['HEUR_VALD']).seconds < T:
            trips.loc[transfer_id, 'unkonwn'] = 'all'
            trips.loc[transfer_id, 'D'] = ''
            trips.loc[transfer_id, 'D_station'] = ''
            trips.loc[transfer_id, 'D_zones'] = ''
            trips.loc[transfer_id, 'D_x'] = ''
            trips.loc[transfer_id, 'D_y'] =''
    return trips,trip_id

In [57]:
def  trip_prediction_no_location(data, n, index, trips, transfer_id):
    i = 0
    trip_id = 0
    start = data.loc[index]     #start would be used in the final trip
    end = data.loc[index+n-1]
    trip_start_time = start['HEUR_VALD']   
    while i+1 < n:
        first = data.loc[index+i]
        second = data.loc[index+i+1]
        first_data = [trip_id, first['NUMR_CART'], first['JOUR_EXPL_VALD'], 
                      first['Lib_Arret'], second['Lib_Arret'], first['HEUR_VALD'], second['HEUR_VALD'], first['COD_TLB_RES'], 
                      first['COD_TLB_ARRT_STTN'],second['COD_TLB_ARRT_STTN'],
                      first['COD_STF_LIGN'], 'd', first['COD_MOD_VALD'], second['COD_MOD_VALD']]
        trips.loc[transfer_id] = first_data
        if second['COD_NATR_VALD'] in sortie:
            trips.loc[transfer_id, 'unkonwn'] = 'no'
            transfer_id = transfer_id + 1 
            i = i + 2
        else:
            trips.loc[transfer_id, 'unkonwn'] = 'd'
            transfer_id = transfer_id + 1
            i = i + 1
            if (second['HEUR_VALD'] - trip_start_time).seconds > T:
                trip_start_time = second['HEUR_VALD']
                trip_id = trip_id + 1
    if (i+1) == n:  # which means the last trip is a 'E'
        if (end['HEUR_VALD'] -  trip_start_time).seconds > T:
            trip_id = trip_id + 1
        last_data = [trip_id, end['NUMR_CART'], end['JOUR_EXPL_VALD'], 
                     end['Lib_Arret'], start['Lib_Arret'], end['HEUR_VALD'], '', 
                     end['COD_TLB_RES'], end['COD_TLB_ARRT_STTN'],start['COD_TLB_ARRT_STTN'], 
                     end['COD_STF_LIGN'], 'd', end['COD_MOD_VALD'], start['COD_MOD_VALD']]
        trips.loc[transfer_id] = last_data
        trips.loc[transfer_id, 'unkonwn'] = 'dh'
        if (end['HEUR_VALD'] - start['HEUR_VALD']).seconds < T:
            trips.loc[transfer_id, 'unkonwn'] = 'all'
            trips.loc[transfer_id, 'D'] = ''
            trips.loc[transfer_id, 'D_station'] = ''
            trips.loc[transfer_id,'D_mode'] = ''
    return trips, transfer_id

In [7]:
path_3 =  'F:/Stage/data/AFC/counts/counts_3'
path_1 = 'F:/Stage/data/AFC/counts/counts_1'
path_arret = "F:/Stage/data/AFC/DM arret.txt"
path_2 = 'F:/Stage/data/AFC/counts/counts_2'
path_4 =  'F:/Stage/data/AFC/counts/counts_4'
path_5 =  'F:/Stage/data/AFC/counts/counts_5'
path_6 =  'F:/Stage/data/AFC/counts/counts_6'
path_7 =  'F:/Stage/data/AFC/counts/counts_7'

In [8]:
data_3 = pd.read_csv(path_3, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [83]:
data_2 = pd.read_csv(path_2, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [84]:
data_4 =  pd.read_csv(path_4, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [85]:
data_5 =  pd.read_csv(path_5, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [86]:
data_6 =  pd.read_csv(path_6, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [87]:
data_7 =  pd.read_csv(path_7, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [98]:
print('1: ', len(data_1))
print('2: ',len(data_2))
print('3: ',len(data_3))
print('4: ',len(data_4))
print('5: ',len(data_5))
print('6: ',len(data_6))
print('7: ',len(data_7))
(len(data_1)+len(data_2)+len(data_3)+len(data_4)+len(data_5)+len(data_6)+len(data_7))/13099451

1:  272716
2:  1471738
3:  1392885
4:  2108756
5:  1973650
6:  1686990
7:  1278816

0.7775555632064275

In [95]:
data_1 = pd.read_csv(path_1, delimiter="\t", header = 0, encoding="latin-1")

E:\python\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
arrets = pd.read_csv(path_arret, delimiter="\t", header= 0, encoding="latin-1")

In [10]:
arrets = arrets[arrets.ZONS_ARRT != 'ND ']
arrets = arrets[arrets.COOR_X_PHSQ != '-1']
arrets = arrets[arrets.COOR_X_PHSQ != '?']

In [11]:
arrets['COOR_X_PHSQ'] = arrets['COOR_X_PHSQ'].apply(lambda x: float((x.split(',')[0])))
arrets['COOR_Y_PHSQ'] = arrets['COOR_Y_PHSQ'].apply(lambda x: float((x.split(',')[0])))

In [12]:
get_counts(arrets['COD_TLB_ARRT_STTN'])

{'1133         ': 13,
 '3244         ': 2,
 '35808        ': 1,
 '16161        ': 1,
 '8320         ': 2,
 '0030010068064': 1,
 '0030010763006': 1,
 '33           ': 57,
 '524          ': 21,
 '45479        ': 1,
 '0030010166009': 1,
 '360          ': 34,
 '1471         ': 10,
 '50828        ': 1,
 '253          ': 33,
 '28242        ': 1,
 '0030010098019': 1,
 '0030010184027': 1,
 '58801        ': 2,
 '268          ': 25,
 '1114         ': 15,
 '50755        ': 1,
 '0030010743038': 1,
 '44           ': 56,
 '1344         ': 13,
 '0030010299028': 1,
 '115          ': 47,
 '36594        ': 1,
 '36           ': 56,
 '338          ': 39,
 '347          ': 42,
 '307          ': 32,
 '556          ': 19,
 '0030010116012': 1,
 '329          ': 34,
 '53571        ': 1,
 '45117        ': 1,
 '1436         ': 9,
 '575          ': 22,
 '558          ': 19,
 '38           ': 54,
 '279          ': 29,
 '0030010157020': 1,
 '0030010396008': 1,
 '34           ': 60,
 '99           ': 45,
 '3146         ': 3,
 '2110         ': 4,
 '32095        ': 1,
 '0030010292059': 1,
 '10259        ': 1,
 '802          ': 10,
 '0030010391008': 1,
 '0030010260022': 1,
 '0030010069046': 1,
 '168          ': 43,
 '404          ': 23,
 '107          ': 47,
 '0030010714093': 1,
 '468          ': 23,
 '529          ': 18,
 '0030010524004': 1,
 '0030010927030': 1,
 '10283        ': 3,
 '1311         ': 14,
 '46321        ': 1,
 '1083         ': 12,
 '1302         ': 15,
 '40133        ': 1,
 '0030010574009': 1,
 '22           ': 71,
 '30614        ': 1,
 '3215         ': 3,
 '769          ': 13,
 '483          ': 22,
 '0030010018010': 1,
 '0030030090700': 1,
 '8361         ': 2,
 '57           ': 51,
 '2332         ': 1,
 '1375         ': 7,
 '0030010734001': 1,
 '320          ': 37,
 '0030010574031': 1,
 '45877        ': 1,
 '65380        ': 1,
 '0030010249029': 1,
 '45           ': 59,
 '370          ': 35,
 '0030010761075': 1,
 '0030010234052': 1,
 '5470         ': 1,
 '0030010086055': 1,
 '2000         ': 7,
 '19120        ': 3,
 '20033        ': 1,
 '250          ': 42,
 '0030010269051': 1,
 '37928        ': 1,
 '0030010238103': 1,
 '446          ': 27,
 '0030010712117': 1,
 '1613         ': 4,
 '195          ': 39,
 '359          ': 27,
 '19503        ': 2,
 '1514         ': 4,
 '0030010186035': 1,
 '0030010702024': 1,
 '35692        ': 1,
 '1291         ': 17,
 '412          ': 29,
 '0030010131013': 1,
 '344          ': 38,
 '0030010259014': 1,
 '36224        ': 1,
 '48           ': 55,
 '0030010367040': 1,
 '0030010017069': 1,
 '393009       ': 1,
 '1367         ': 10,
 '193          ': 40,
 '0030010137002': 1,
 '196          ': 38,
 '3260         ': 3,
 '517          ': 28,
 '0030010250031': 1,
 '0030010744046': 1,
 '1091         ': 12,
 '1336         ': 9,
 '861          ': 8,
 '0030010378034': 1,
 '37443        ': 1,
 '0030010290026': 1,
 '317          ': 37,
 '357          ': 28,
 '0030010340007': 1,
 '183          ': 50,
 '0030010541034': 1,
 '0030010546034': 1,
 '1143         ': 12,
 '0030010181035': 1,
 '653          ': 9,
 '19534        ': 1,
 '104          ': 46,
 '1117         ': 16,
 '50513        ': 1,
 '139          ': 42,
 '0030010097016': 1,
 '0030010216025': 1,
 '0030010169015': 1,
 '135          ': 51,
 '271          ': 39,
 '129          ': 46,
 '198          ': 48,
 '2783         ': 4,
 '464          ': 27,
 '20182        ': 1,
 '0030010250045': 1,
 '12           ': 82,
 '1570         ': 7,
 '29           ': 64,
 '328          ': 33,
 '0030010721135': 1,
 '241          ': 39,
 '30080        ': 1,
 '52           ': 47,
 '0030010274011': 1,
 '554          ': 20,
 '613          ': 27,
 '424          ': 25,
 '0030010535011': 1,
 '18133        ': 2,
 '0030010068014': 1,
 '795          ': 7,
 '586          ': 20,
 '530          ': 21,
 '0030010585004': 1,
 '1157         ': 14,
 '0030030130100': 1,
 '109          ': 47,
 '184          ': 44,
 '0030010556019': 1,
 '110          ': 50,
 '635          ': 21,
 '345          ': 32,
 '0030010544007': 1,
 '50752        ': 1,
 '691          ': 15,
 '1147         ': 13,
 '0030010330044': 1,
 '19454        ': 3,
 '0030010303004': 1,
 '23780        ': 1,
 '1146         ': 14,
 '815          ': 6,
 '0030010576027': 1,
 '216          ': 35,
 '0030010731139': 1,
 '0030010026072': 1,
 '0030010098053': 1,
 '1267         ': 14,
 '37           ': 55,
 '0030010393024': 1,
 '0030010741024': 1,
 '19126        ': 2,
 '2001         ': 8,
 '1604         ': 2,
 '36148        ': 1,
 '0030010742002': 1,
 '0030010212050': 1,
 '40140        ': 1,
 '754          ': 10,
 '0030010080015': 1,
 '16           ': 79,
 '19524        ': 1,
 '37696        ': 1,
 '19468        ': 1,
 '1256         ': 14,
 '0030010174098': 1,
 '407          ': 29,
 '0030010080065': 1,
 '0030010291010': 1,
 '1368         ': 10,
 '0030010715100': 1,
 '0030010194045': 1,
 '0030010133062': 1,
 '0030010169065': 1,
 '437          ': 33,
 '19529        ': 1,
 '0030010039064': 1,
 '258          ': 33,
 '0030010715041': 1,
 '0030010039014': 1,
 '582          ': 23,
 '0030010195028': 1,
 '0030010358067': 1,
 '605          ': 24,
 '0030010762072': 1,
 '1014         ': 19,
 '0030010238107': 1,
 '178          ': 38,
 '0030010249007': 1,
 '0030010171042': 1,
 '0030010075039': 1,
 '711          ': 17,
 '51031        ': 1,
 '36219        ': 1,
 '5902         ': 1,
 '0030010117037': 1,
 '3            ': 83,
 '0030010138004': 1,
 '1248         ': 13,
 '0030010379014': 1,
 '0030010920014': 1,
 '0030010361079': 1,
 '1053         ': 8,
 '1101         ': 13,
 '0030010289014': 1,
 '27231        ': 1,
 '10           ': 84,
 '690          ': 15,
 '333          ': 28,
 '0030010753049': 1,
 '0030010702005': 1,
 '1582         ': 9,
 '680          ': 17,
 '0030010269073': 1,
 '0030010176042': 1,
 '113          ': 48,
 '0030010921054': 1,
 '0030010111012': 1,
 '49           ': 56,
 '0030010566028': 1,
 '0030010367035': 1,
 '0030010111062': 1,
 '25           ': 68,
 '35852        ': 1,
 '1320         ': 7,
 '0030010302031': 1,
 '266          ': 31,
 '694          ': 17,
 '0030010092023': 1,
 '316          ': 33,
 '0030010262054': 1,
 '145          ': 46,
 '55           ': 48,
 '0030010133012': 1,
 '442          ': 24,
 '243          ': 33,
 '336          ': 29,
 '1224         ': 7,
 '86           ': 44,
 '50600        ': 5,
 '0030010131063': 1,
 '1985         ': 4,
 '39           ': 52,
 '187          ': 41,
 '469          ': 21,
 '0030010074004': 1,
 '1314         ': 10,
 '78           ': 47,
 '36231        ': 1,
 '0030010123051': 1,
 '0030010105011': 1,
 '2447         ': 1,
 '0030010185055': 1,
 '0030010350030': 1,
 '77           ': 47,
 '531          ': 21,
 '40196        ': 1,
 '0030010199013': 1,
 '905          ': 7,
 '2295         ': 2,
 '1362         ': 10,
 '0030010355001': 1,
 '0030010017057': 1,
 '124          ': 46,
 '102          ': 48,
 '1196         ': 10,
 '0030010920064': 1,
 '37135        ': 1,
 '17           ': 73,
 '0030010261002': 1,
 '20144        ': 1,
 '1602         ': 4,
 '0030010741005': 1,
 '0030010119058': 1,
 '1180         ': 16,
 '0030010278017': 1,
 '2711         ': 2,
 '0030010301052': 1,
 '491          ': 30,
 '356          ': 37,
 '677          ': 13,
 '688          ': 14,
 '0030010358017': 1,
 '0030010007048': 1,
 '27887        ': 2,
 '1017         ': 15,
 '0030010060011': 1,
 '45280        ': 1,
 '0030010563025': 1,
 '136          ': 42,
 '32           ': 64,
 '37905        ': 1,
 '0030010058042': 1,
 '1154         ': 14,
 '61501        ': 1,
 '1106         ': 18,
 '427          ': 29,
 '21           ': 70,
 '35840        ': 1,
 '0030010199017': 1,
 '18062        ': 2,
 '1041         ': 19,
 '0030010092027': 1,
 '421          ': 30,
 '260          ': 33,
 '38120        ': 1,
 '8293         ': 3,
 '19340        ': 1,
 '0030010341009': 1,
 '0030010259064': 1,
 '45509        ': 1,
 '19065        ': 2,
 '289          ': 33,
 '0030010571027': 1,
 '0030010020024': 1,
 '137          ': 51,
 '428          ': 28,
 '0030010161009': 1,
 '0030010713115': 1,
 '1049         ': 11,
 '2055         ': 4,
 '0030010187020': 1,
 '0030010393005': 1,
 '0030010254010': 1,
 '0030010206050': 1,
 '0030010096028': 1,
 '455          ': 22,
 '98           ': 48,
 '5393         ': 2,
 '0030010123020': 1,
 '0030010043002': 1,
 '1042         ': 20,
 '853          ': 13,
 '0030010070029': 1,
 '0030010047043': 1,
 '0030010052035': 1,
 '0030010713096': 1,
 '633          ': 19,
 '561          ': 22,
 '19128        ': 2,
 '0030010153026': 1,
 '37563        ': 1,
 '0030010056014': 1,
 '0030010360052': 1,
 '0030010714048': 1,
 '0030010732015': 1,
 '1145         ': 15,
 '163          ': 43,
 '750          ': 16,
 '0030050181004': 1,
 '378          ': 28,
 '8059         ': 2,
 '549          ': 14,
 '0030030251500': 1,
 '0030010714106': 1,
 '0030010354008': 1,
 '0030010186040': 1,
 '636          ': 17,
 '0030010117033': 1,
 '22593        ': 1,
 '386003       ': 1,
 '222          ': 40,
 '546          ': 19,
 '0030010174019': 1,
 '30164        ': 2,
 '0030010251044': 1,
 '0030010341031': 1,
 '429          ': 27,
 '797          ': 10,
 '1611         ': 7,
 '151          ': 46,
 '0030010790011': 1,
 '0030010399058': 1,
 '0030010187051': 1,
 '2443         ': 3,
 '164798       ': 1,
 '0030010796051': 1,
 '1100         ': 18,
 '966          ': 7,
 '138          ': 46,
 '0030010289090': 1,
 '0030010586019': 1,
 '8            ': 80,
 '0030010214004': 1,
 '150          ': 44,
 '1262         ': 13,
 '726          ': 16,
 '1372         ': 9,
 '0030010346009': 1,
 '0030010389009': 1,
 '51           ': 53,
 '0030010173028': 1,
 '0030010713165': 1,
 '0030010194032': 1,
 '172          ': 39,
 '46290        ': 1,
 '3199         ': 2,
 '1161         ': 10,
 '31591        ': 1,
 '38994        ': 1,
 '310          ': 38,
 '0030010278013': 1,
 '758          ': 11,
 '51160        ': 1,
 '0030010070007': 1,
 '286          ': 28,
 '37832        ': 1,
 '0030010027018': 1,
 '0030010175009': 1,
 '288          ': 28,
 '0030010520003': 1,
 '0030010094052': 1,
 '111          ': 51,
 '0030010275001': 1,
 '0030010267042': 1,
 '175          ': 46,
 '50611        ': 1,
 '789          ': 8,
 '2184         ': 2,
 '0030010208032': 1,
 '0030010017019': 1,
 '395          ': 36,
 '1546         ': 4,
 '38082        ': 1,
 '0030010098057': 1,
 '0030010295036': 1,
 '80           ': 45,
 '0030010060061': 1,
 '1295         ': 11,
 '354          ': 32,
 '0030010030031': 1,
 '0030010796020': 1,
 '0030010174057': 1,
 '19557        ': 1,
 '0030010713159': 1,
 '45013        ': 1,
 '0030010391012': 1,
 '297          ': 31,
 '2302         ': 3,
 '18051        ': 2,
 '35043        ': 1,
 '0030010358063': 1,
 '0030010724013': 1,
 '0030010291006': 1,
 '0030010924011': 1,
 '0030010714097': 1,
 '0030010081014': 1,
 '18074        ': 2,
 '20085        ': 1,
 '294          ': 33,
 '0030010056064': 1,
 '0030010370031': 1,
 '326          ': 30,
 '600          ': 34,
 '0030010131017': 1,
 '6837         ': 1,
 '35065        ': 1,
 '557          ': 20,
 '46301        ': 1,
 '7528         ': 1,
 '54271        ': 1,
 '66           ': 49,
 '123          ': 42,
 '64           ': 46,
 '230          ': 36,
 '978          ': 12,
 '901          ': 9,
 '386          ': 35,
 '0030010147010': 1,
 '54131        ': 1,
 '30710        ': 1,
 '0030010289105': 1,
 '82           ': 40,
 '4126         ': 1,
 '0030010268044': 1,
 '0030010714037': 1,
 '9030         ': 5,
 '125          ': 43,
 '0030010020005': 1,
 '97           ': 48,
 '67           ': 46,
 '0030010080059': 1,
 '0030010269020': 1,
 '46           ': 55,
 '0030010396012': 1,
 '19442        ': 1,
 '0030010206041': 1,
 '6002         ': 2,
 '217          ': 35,
 '36173        ': 1,
 '53           ': 48,
 '0030010308030': 1,
 '0030010244028': 1,
 '0030010185014': 1,
 '0030010721140': 1,
 '18032        ': 2,
 '214          ': 41,
 '471          ': 26,
 '0030010771004': 1,
 '601          ': 31,
 '142          ': 40,
 '14561        ': 1,
 '35981        ': 1,
 '0030010580013': 1,
 '9499         ': 1,
 '0030010385001': 1,
 '38069        ': 1,
 '1067         ': 11,
 '0030010070003': 1,
 '0030010312052': 1,
 '43           ': 56,
 '0030010389031': 1,
 '26           ': 64,
 '0030010358013': 1,
 '0030010212041': 1,
 '116          ': 48,
 '702          ': 14,
 '334          ': 31,
 '580          ': 22,
 '0030010086014': 1,
 '0030010116062': 1,
 '276          ': 35,
 '0030010144067': 1,
 '509          ': 29,
 '0030010091028': 1,
 '68           ': 46,
 '642          ': 15,
 '41362        ': 1,
 '0030010289064': 1,
 '0030010318041': 1,
 '489          ': 32,
 '8030         ': 2,
 '0030010220146': 1,
 '0030010268068': 1,
 '0030010295047': 1,
 '0030010320088': 1,
 '0030010256018': 1,
 '0030010302045': 1,
 '1376         ': 8,
 '0030010177050': 1,
 '0030010175076': 1,
 '0030010720046': 1,
 '3341         ': 3,
 '0030010178024': 1,
 '571          ': 21,
 '921          ': 8,
 '36116        ': 1,
 '9688         ': 1,
 '0030010396062': 1,
 '0030010712079': 1,
 '35155        ': 1,
 '59           ': 49,
 '337          ': 37,
 '0030010183026': 1,
 '16928        ': 1,
 '3093         ': 3,
 '944          ': 4,
 '61           ': 50,
 '96           ': 43,
 '0030010210029': 1,
 '37465        ': 1,
 '0030010310015': 1,
 '477          ': 26,
 '0030010185064': 1,
 '0030010072041': 1,
 '2576         ': 2,
 '37149        ': 1,
 '2004         ': 5,
 '0030010256068': 1,
 '0030010791020': 1,
 '2771         ': 2,
 '788          ': 10,
 '37856        ': 1,
 '0030010047047': 1,
 '368          ': 32,
 '850          ': 10,
 '212          ': 46,
 '0030010318042': 1,
 '37974        ': 1,
 '445          ': 29,
 '0030030121400': 1,
 '19430        ': 1,
 '684217       ': 1,
 '50           ': 54,
 '1070         ': 15,
 '51670        ': 1,
 '264          ': 38,
 '0030010066020': 1,
 '0030010388017': 1,
 '143          ': 34,
 '0030010157052': 1,
 '101          ': 48,
 '18119        ': 1,
 '9220         ': 2,
 '56           ': 49,
 '0030010333014': 1,
 '0030010160007': 1,
 '1257         ': 14,
 '58080        ': 1,
 '55490        ': 1,
 '10643        ': 1,
 '1349         ': 16,
 '30040        ': 2,
 '30           ': 70,
 '20219        ': 1,
 '0030010513011': 1,
 '847          ': 6,
 '0030010346045': 1,
 '0030010530036': 1,
 '233          ': 35,
 '0030010390056': 1,
 '20284        ': 1,
 '0030010048039': 1,
 '73           ': 49,
 '71           ': 55,
 '0030010515005': 1,
 '0030010238038': 1,
 '0030010530043': 1,
 '0030010279031': 1,
 '0030010144017': 1,
 '0030010174053': 1,
 '1038         ': 15,
 '36691        ': 1,
 '1077         ': 12,
 '158          ': 37,
 '38159        ': 1,
 '776          ': 14,
 '0030010732065': 1,
 '0030010306052': 1,
 '619          ': 13,
 '11005        ': 1,
 '0030010054028': 1,
 '0030010399026': 1,
 '134          ': 42,
 '22277        ': 1,
 '14829        ': 1,
 '169          ': 41,
 '0030010361094': 1,
 '192          ': 40,
 '313          ': 30,
 '1097         ': 11,
 '384          ': 34,
 '185          ': 43,
 '0030010589034': 1,
 '27967        ': 1,
 '19588        ': 2,
 '91           ': 43,
 '0030010007033': 1,
 '0030010535008': 1,
 '1331         ': 10,
 '0030010111099': 1,
 '303          ': 33,
 '13           ': 84,
 '0030010104044': 1,
 '53001        ': 1,
 '0030010017053': 1,
 '1498         ': 10,
 '682252       ': 1,
 '1148         ': 11,
 '0030010268018': 1,
 '298          ': 32,
 '2620         ': 2,
 '934          ': 6,
 '11915        ': 1,
 '140          ': 44,
 '0030010161031': 1,
 '0030010144013': 1,
 '0030010150039': 1,
 '0030010147120': 1,
 '45675        ': 1,
 '10519        ': 2,
 '805          ': 11,
 '45057        ': 1,
 '23           ': 67,
 '0030010579017': 1,
 '261          ': 34,
 '0030010211009': 1,
 '3156         ': 3,
 '0030010027044': 1,
 '623          ': 16,
 '738          ': 15,
 '5333         ': 2,
 '0030010032017': 1,
 '539          ': 16,
 '1713         ': 2,
 '417          ': 25,
 '226          ': 33,
 '0030010239044': 1,
 '0030010166045': 1,
 '924          ': 8,
 '577          ': 22,
 '282          ': 27,
 '1126         ': 11,
 '3144         ': 2,
 '461          ': 31,
 '0030010302032': 1,
 '0030010207021': 1,
 '0030010028023': 1,
 '60           ': 47,
 '0030010104018': 1,
 '0030010239018': 1,
 '0030010183058': 1,
 '283          ': 35,
 '19138        ': 2,
 '19164        ': 1,
 '153          ': 46,
 '5004         ': 3,
 '314          ': 30,
 '0030010030045': 1,
 '52941        ': 1,
 '418          ': 24,
 '0030010234035': 1,
 '0030010122056': 1,
 '0030010088042': 1,
 '5030         ': 4,
 '53320        ': 1,
 '204          ': 43,
 '51970        ': 1,
 '0030010061020': 1,
 '0030010301040': 1,
 '49971        ': 1,
 '89           ': 43,
 '205          ': 40,
 '5851         ': 3,
 '53560        ': 2,
 '240          ': 38,
 '252          ': 38,
 '1170         ': 14,
 '219          ': 35,
 '0030010330018': 1,
 '51500        ': 2,
 '58           ': 53,
 '15           ': 85,
 '0030010024021': 1,
 '0030010724063': 1,
 '0030010174069': 1,
 '538          ': 20,
 '579          ': 21,
 '156          ': 36,
 '45088        ': 1,
 '0030010047036': 1,
 '5987         ': 1,
 '0030010145007': 1,
 '506          ': 21,
 '0030010148025': 1,
 '0030010762004': 1,
 '0030010735043': 1,
 '0030010220028': 1,
 '5            ': 86,
 '0030010299056': 1,
 '17380        ': 1,
 '0030010714033': 1,
 '1140         ': 17,
 '0030010745113': 1,
 '75           ': 44,
 '0030010021004': 1,
 '1171         ': 10,
 '35924        ': 1,
 '0030010732089': 1,
 '510          ': 33,
 '658          ': 14,
 '1087         ': 11,
 '29511        ': 1,
 '0030010249003': 1,
 '6639         ': 1,
 '0030010559034': 1,
 '20346        ': 1,
 '0030010162042': 1,
 '0030010530047': 1,
 '300          ': 38,
 '45611        ': 1,
 '47           ': 58,
 '291          ': 31,
 '32991        ': 1,
 '149          ': 41,
 '534          ': 15,
 '0030010120017': 1,
 '51030        ': 2,
 '0030010102021': 1,
 '0030010501016': 1,
 '610          ': 25,
 '771          ': 18,
 '855          ': 10,
 '761          ': 11,
 '2048         ': 5,
 '523          ': 23,
 '165          ': 40,
 '148          ': 42,
 '35741        ': 1,
 '281          ': 30,
 '755          ': 9,
 '0030010046029': 1,
 '0030010515024': 1,
 '1            ': 84,
 '10239        ': 2,
 '982          ': 9,
 '1221         ': 14,
 '0030010274008': 1,
 '0030010320111': 1,
 '37305        ': 1,
 '32640        ': 1,
 '439          ': 30,
 '0030010143158': 1,
 '0030010032013': 1,
 '19428        ': 2,
 '0030010279009': 1,
 '36295        ': 1,
 '0030010164058': 1,
 '5335         ': 2,
 '0030010125004': 1,
 '295          ': 33,
 '3276         ': 4,
 '0030010110033': 1,
 '1155         ': 10,
 '1055         ': 11,
 '443          ': 24,
 '465          ': 28,
 '1234         ': 10,
 '0030010174103': 1,
 '122          ': 45,
 '1525         ': 4,
 '40120        ': 1,
 '0030010389045': 1,
 '481          ': 26,
 '0030010144063': 1,
 '0030010105012': 1,
 '0030010372017': 1,
 '0030010711084': 1,
 '304          ': 35,
 '35314        ': 1,
 '0030010272034': 1,
 '0030010145029': 1,
 '3247         ': 1,
 '4056         ': 2,
 '0030010251018': 1,
 '0030010520007': 1,
 '1682         ': 3,
 '0030010594048': 1,
 '0030010394034': 1,
 '0030010325043': 1,
 '383          ': 31,
 '0030010594056': 1,
 '0030010304023': 1,
 '1402         ': 11,
 '14441        ': 1,
 '697          ': 16,
 '516          ': 34,
 '1965         ': 1,
 '322          ': 31,
 '498          ': 25,
 '51790        ': 2,
 '0030010112049': 1,
 '0030010105008': 1,
 '1026         ': 12,
 '5021         ': 1,
 '18           ': 67,
 '331          ': 33,
 '0030010751028': 1,
 '45409        ': 1,
 '36967        ': 1,
 '474          ': 20,
 '352          ': 32,
 '269          ': 39,
 '119          ': 39,
 '0030010093025': 1,
 '0030010147060': 1,
 '0030010191036': 1,
 '0030010042006': 1,
 '6011         ': 1,
 '0030010790012': 1,
 '0030010114034': 1,
 '1244         ': 11,
 '1330         ': 11,
 '0030010143126': 1,
 '0030010526009': 1,
 '116244       ': 1,
 '1542         ': 5,
 '0030010076009': 1,
 '0030010031044': 1,
 '0030010143016': 1,
 '238          ': 32,
 '0030010722055': 1,

In [9]:
data_3['COD_NATR_VALD'] = data_3['COD_NATR_VALD'].astype('str')
data_3['HEUR_VALD'] = pd.to_timedelta(data_3['HEUR_VALD'])
data_3_sort = data_3.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_3_sort = data_3_sort.reset_index(drop = True)

In [15]:
data_3_sort[data_3_sort['COD_NATR_VALD'].isin(sortie_c)]

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
37,2460846,99997027328529013521,14/03/2017,18:16:55,GARE DE LYON,1,801,0030050091300,215,57,3,810,801,ND
86,2966580,99994402105613089205,14/03/2017,14:52:08,BOULAINVILLIERS,2,2,543181,39550004,4,3,800,803,ND
101,2340876,99993844160407781116,14/03/2017,16:28:55,GARE DE LYON,1,801,0030050091300,319,57,3,810,801,ND
193,1026848,99987634174763920579,14/03/2017,14:40:29,CHAMP DE MARS-TOUR EIFFEL,2,002,393058,16640101,4,3,800,803,ND
215,478565,99986555675739770561,14/03/2017,14:41:51,CHATELET-LES HALLES,1,801,0030050011000,212,57,3,810,801,ND
260,9442878,99983482563385410830,14/03/2017,17:16:18,MAGENTA,2,002,281873,24500106,4,3,800,805,ND
310,2586792,99980051941501145009,14/03/2017,09:16:42,HAUSSMANN-SAINT-LAZARE,2,002,281899,3500007,4,3,800,805,ND
337,286100,99978004583900887928,14/03/2017,07:46:25,BIBLIOTHEQUE FRANCOIS MITTERRAND,2,002,328328,14410301,4,3,800,803,ND
361,3922465,99976044653000885872,14/03/2017,08:34:24,HAUSSMANN-SAINT-LAZARE,2,002,281899,26500004,4,3,800,805,ND
368,5594109,99975746170079595931,14/03/2017,16:06:34,GARE DU NORD,2,002,271007,225500102,4,3,800,853,ND
383,4671173,99974070044150110637,14/03/2017,15:59:34,CHARLES DE GAULLE ETOILE,1,801,0030050170101,206,57,3,810,801,ND
466,3071485,99967092866084336806,14/03/2017,16:52:11,HAUSSMANN-SAINT-LAZARE,2,2,281899,24500007,4,3,800,805,ND
613,1248396,99952133291214812304,14/03/2017,09:42:23,HAUSSMANN-SAINT-LAZARE,2,2,281899,26500004,4,3,800,805,ND
633,1335123,99950251859620141268,14/03/2017,05:36:17,HAUSSMANN-SAINT-LAZARE,2,002,281899,20500004,4,3,800,805,ND
679,8758654,99946881114150654931,14/03/2017,07:16:32,GARE DU NORD,2,002,271007,211500102,4,3,800,853,ND
734,12548103,99942113514081512969,14/03/2017,20:00:40,AUBER,1,801,0030050060600,320,057,3,810,801,ND
857,8555194,99934335514676299377,14/03/2017,23:13:07,GARE DU NORD,2,002,271007,224500102,4,3,800,853,ND
900,6985819,99931556434874836935,14/03/2017,06:11:18,LA CHAPELLE,3,001,0030030220900,332,57,3,100,110,ND
964,2247523,99926349333604614474,14/03/2017,08:42:57,LA DEFENSE-GRANDE ARCHE,3,1,0030030291100,202,57,3,100,110,ND
1077,4379961,99919190390893654736,14/03/2017,09:25:57,LA DEFENSE-GRANDE ARCHE,3,001,0030030291100,212,57,3,100,110,ND
1194,8634351,99910813095401155072,14/03/2017,06:49:53,GARE DU NORD,2,002,271007,217500102,4,3,800,853,ND
1237,1082149,99906984028191873063,14/03/2017,09:11:21,GARE DE LYON,1,801,0030050091300,315,57,3,810,801,ND
1252,4042838,99905745721381059483,14/03/2017,09:20:15,BOULAINVILLIERS,2,002,543181,41550004,4,3,800,803,ND
1258,649532,99904728277081409146,14/03/2017,09:24:52,LA DEFENSE-GRANDE ARCHE,3,001,0030030291100,304,57,3,100,110,ND
1332,8372205,99901115824602767987,14/03/2017,09:40:29,GARE DU NORD,2,002,271007,211500102,4,3,800,853,ND
1339,1355359,99900432977822920540,14/03/2017,09:24:58,CHATELET-LES HALLES,1,801,0030050011000,306,57,3,810,801,ND
1443,7309583,99893419525720385279,14/03/2017,16:23:36,LA CHAPELLE,3,001,0030030220900,332,57,3,100,110,ND
1447,293418,99893210753036596933,14/03/2017,07:51:10,BIBLIOTHEQUE FRANCOIS MITTERRAND,2,002,328328,34410301,4,3,800,803,ND
1449,8292954,99893197520576750780,14/03/2017,08:07:07,LA CHAPELLE,3,001,0030030220900,331,57,3,100,110,ND
1535,4039071,99885759371344508788,14/03/2017,10:55:52,GARE DE LYON,1,801,0030050091300,215,57,3,810,801,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1391628,6267497,00096014869950697430,14/03/2017,08:45:20,GARE DU NORD,2,002,271007,223500102,4,3,800,853,ND
1391676,4594097,00091217325064980182,14/03/2017,09:05:10,BIBLIOTHEQUE FRANCOIS MITTERRAND,2,002,328328,31410301,4,3,800,803,ND
1391721,5064315,00087312356652359466,14/03/2017,09:34:28,GARE DU NORD,2,002,271007,213500102,4,3,800,853,ND
1391727,8374612,00087041708300630423,14/03/2017,06:06:43,DENFERT-ROCHEREAU,1,802,0030050151300,245,57,3,810,802,ND
1391735,5712429,00086728170678236049,14/03/2017,19:49:31,DENFERT-ROCHEREAU,1,802,0030050151300,147,57,3,810,802,ND
1391955,10431450,00070508226049282295,14/03/2017,05:58:03,AUBER,1,801,0030050060600,304,57,3,810,801,ND
1392028,6938951,00065074798324880600,14/03/2017,06:33:03,GARE DU NORD,2,002,271007,216500102,4,3,800,853,ND
1392035,8272295,00064825475088226560,14/03/2017,19:50:04,DENFERT-ROCHEREAU,1,802,0030050151300,144,57,3,810,802,ND
1392060,2792402,00062129926999712804,14/03/2017,08:15:52,GARE DE LYON,1,801,0030050091300,217,57,3,810,801,ND
1392136,442562,00057010716104312971,14/03/2017,08:56:31,NATION,1,801,0030050160101,304,57,3,810,801,ND
1392157,2887073,00055050644873349734,14/03/2017,09:08:44,HAUSSMANN-SAINT-LAZARE,2,002,281899,26500004,4,3,800,805,ND
1392172,9506631,00052598807093450955,14/03/2017,08:38:47,AUBER,1,801,0030050060600,316,57,3,810,801,ND
1392182,3492577,00051818845044989947,14/03/2017,10:12:39,CHARLES DE GAULLE ETOILE,1,801,0030050170101,202,57,3,810,801,ND
1392196,2577186,00051034145350182224,14/03/2017,21:54:10,GARE DE LYON,1,801,0030050091300,314,57,3,810,801,ND
1392202,6113743,00050519010632574289,14/03/2017,20:37:30,LA DEFENSE-GRANDE ARCHE,2,002,382218,12300405,4,3,800,854,ND
1392230,2656685,00048565037642272372,14/03/2017,19:44:50,GARE DE LYON,1,801,0030050091300,147,57,3,810,801,ND
1392391,1506821,00037340221205927391,14/03/2017,09:43:25,HAUSSMANN-SAINT-LAZARE,2,2,281899,26500004,4,3,800,805,ND
1392418,938311,00036211397697725854,14/03/2017,06:53:33,GARE DE LYON,1,801,0030050091300,318,57,3,810,801,ND
1392543,305407,00025601966825785469,14/03/2017,08:55:39,BIBLIOTHEQUE FRANCOIS MITTERRAND,2,002,328328,30410301,4,3,800,803,ND
1392564,4719251,00023303297956680995,14/03/2017,07:58:25,GARE DE LYON,1,801,0030050091300,141,57,3,810,801,ND
1392574,701137,00022113714249575489,14/03/2017,07:46:22,GARE DE LYON,1,801,0030050091300,314,57,3,810,801,ND
1392598,4032315,00021214576293073371,14/03/2017,08:37:38,GARE DE LYON,1,801,0030050091300,141,57,3,810,801,ND
1392622,4707419,00019967469627593570,14/03/2017,08:15:58,HAUSSMANN-SAINT-LAZARE,2,002,281899,26500004,4,3,800,805,ND
1392715,8828600,00013270813436082961,14/03/2017,07:27:24,GARE DU NORD,2,002,271007,225500102,4,3,800,853,ND
1392726,11172588,00010261233122839038,14/03/2017,18:14:13,MAGENTA,2,002,281873,25500106,4,3,800,805,ND
1392743,1309377,00009042724675217032,14/03/2017,20:20:50,INVALIDES,3,001,0030030100900,145,57,3,100,110,ND
1392746,6447365,00008693825405237374,14/03/2017,20:06:26,LA CHAPELLE,3,001,0030030220900,334,57,3,100,110,ND
1392801,1578615,00004478098108028807,14/03/2017,09:20:40,GARE DE LYON,1,801,0030050091300,142,57,3,810,801,ND
1392807,1107665,00004208745468920628,14/03/2017,10:32:31,GARE DE LYON,1,801,0030050091300,243,57,3,810,801,ND
1392850,5158860,00001966593680911043,14/03/2017,00:49:27,GARE DU NORD,2,002,271007,214500102,4,3,800,853,ND

In [21]:
data_3_sort[data_3_sort['NUMR_CART'] =='00051818845044989947' ]

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
1392180,7856585,00051818845044989947,14/03/2017,10:00:43,QUATRE SEPTEMBRE,3,001,0030030060400,102,31,3,100,110,ND
1392181,12027961,00051818845044989947,14/03/2017,10:06:27,AUBER,1,801,0030050060600,121,56,1,810,801,ND
1392182,3492577,00051818845044989947,14/03/2017,10:12:39,CHARLES DE GAULLE ETOILE,1,801,0030050170101,202,57,3,810,801,ND

In [22]:
data_3_sort[data_3_sort['NUMR_CART'] =='00050519010632574289' ]

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
1392201,1499991,00050519010632574289,14/03/2017,20:29:00,CHARLES DE GAULLE ETOILE,1,801,0030050170101,111,51,1,810,801,ND
1392202,6113743,00050519010632574289,14/03/2017,20:37:30,LA DEFENSE-GRANDE ARCHE,2,002,382218,12300405,4,3,800,854,ND
1392203,10283623,00050519010632574289,14/03/2017,20:37:55,LA DEFENSE-GRANDE ARCHE,1,801,0030050170401,304,52,1,810,801,ND

In [14]:
data_2['COD_NATR_VALD'] = data_2['COD_NATR_VALD'].astype('str')
data_2['HEUR_VALD'] = pd.to_timedelta(data_2['HEUR_VALD'])
data_2_sort = data_2.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_2_sort = data_2_sort.reset_index(drop = True)

In [38]:
data_4['COD_NATR_VALD'] = data_4['COD_NATR_VALD'].astype('str')
data_4['HEUR_VALD'] = pd.to_timedelta(data_4['HEUR_VALD'])
data_4_sort = data_4.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_4_sort = data_4_sort.reset_index(drop = True)

In [47]:
data_5['COD_NATR_VALD'] = data_5['COD_NATR_VALD'].astype('str')
data_5['HEUR_VALD'] = pd.to_timedelta(data_5['HEUR_VALD'])
data_5_sort = data_5.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_5_sort = data_5_sort.reset_index(drop = True)

In [55]:
data_6['COD_NATR_VALD'] = data_6['COD_NATR_VALD'].astype('str')
data_6['HEUR_VALD'] = pd.to_timedelta(data_6['HEUR_VALD'])
data_6_sort = data_6.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_6_sort = data_6_sort.reset_index(drop = True)

In [65]:
data_7['COD_NATR_VALD'] = data_7['COD_NATR_VALD'].astype('str')
data_7['HEUR_VALD'] = pd.to_timedelta(data_7['HEUR_VALD'])
data_7_sort = data_7.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_7_sort = data_7_sort.reset_index(drop = True)

In [15]:
data_2_sort

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
0,8394921,99999910079519014654,14/03/2017,08:38:00,Solférino,156,56,180,1202,11,2,56,356,28
1,4072097,99999910079519014654,14/03/2017,17:11:00,Saint Exupery,156,56,370,2953,11,2,56,356,28
2,4999909,99999871953842078691,14/03/2017,07:39:00,Gare SNCF,167,67,273,10578,11,2,67,67,12
3,4999997,99999871953842078691,14/03/2017,08:01:00,Coubertin,167,67,52,10014,11,2,67,67,12
4,5060627,99999834312022823315,14/03/2017,07:44:37,GENTILLY,1,802,0030050180201,331,51,1,810,802,ND
5,5060715,99999834312022823315,14/03/2017,08:04:07,GARE DU NORD,2,002,271007,109500101,2,1,800,853,ND
6,3954024,99999641142476692661,14/03/2017,07:33:08,MOUTON - DUVERNET,3,001,0030010038003,4124,11,2,100,100,38
7,8291016,99999641142476692661,14/03/2017,16:26:50,LUXEMBOURG,3,001,0030010038039,12166,11,2,100,100,38
8,5744932,99999341872786484931,14/03/2017,00:09:57,ECOLE MILITAIRE,3,001,0030030100700,103,31,3,100,110,ND
9,5744844,99999341872786484931,14/03/2017,15:23:04,OURCQ,3,001,0030030220200,102,31,3,100,110,ND
10,966841,99999319654609556985,14/03/2017,09:20:47,SAINT-JACQUES,3,1,0030030150900,102,31,3,100,110,ND
11,5623801,99999319654609556985,14/03/2017,13:32:48,NATIONALE,3,001,0030030141100,104,31,3,100,110,ND
12,11425351,99999279653049637534,14/03/2017,06:43:16,LIEUSAINT-MOISSY,2,002,682153,22431201,1,1,800,804,ND
13,2773807,99999279653049637534,14/03/2017,15:57:54,PORT ROYAL,1,802,0030050151200,102,51,1,810,802,ND
14,12138357,99999259795036239003,14/03/2017,17:20:56,EGLISE DE BOULOGNE-BILLANCOURT,3,001,0030010123031,3583,11,2,100,100,123
15,3688773,99999259795036239003,14/03/2017,17:34:52,MARCEL SEMBAT-METRO,3,001,0030010126029,4062,11,2,100,100,126
16,9167771,99999206973859506317,14/03/2017,07:45:24,ALESIA - GENERAL LECLERC,3,001,0030010068010,1832,11,2,100,100,68
17,173643,99999206973859506317,14/03/2017,17:13:32,PALAIS ROYAL - MUSEE DU LOUVRE,3,001,0030010072039,5599,11,2,100,100,72
18,9524080,99999010865143272586,14/03/2017,08:57:02,PORTE DE CHOISY,3,001,0030010013028,17411,41,4,100,112,13
19,602376,99999010865143272586,14/03/2017,19:08:22,PONT DU GARIGLIANO,3,1,0030010013026,20389,41,4,100,112,13
20,8373565,99998956624718552818,14/03/2017,07:13:52,CONVENTION,3,001,0030030160500,104,31,3,100,110,ND
21,4048453,99998956624718552818,14/03/2017,17:38:44,STALINGRAD,3,001,0030030221100,101,31,3,100,110,ND
22,7475736,99998788673029678967,14/03/2017,08:21:40,MAURICE LACHATRE,3,001,0030010921038,6973,41,4,100,112,11
23,7475824,99998788673029678967,14/03/2017,08:28:32,HOPITAL AVICENNE,3,001,0030010921012,19702,41,4,100,112,11
24,990550,99998699026613170093,14/03/2017,07:38:16,GAMBETTA,3,1,0030030241000,102,31,3,100,110,ND
25,9889022,99998699026613170093,14/03/2017,17:40:09,CRETEIL-PREFECTURE (HOTEL DE VILLE),3,001,0030030250700,104,31,3,100,110,ND
26,7078657,99998501482912656386,14/03/2017,08:50:28,PORTE DE CHAMPERRET,3,001,0030010163001,1062,11,2,100,100,163
27,7078745,99998501482912656386,14/03/2017,18:45:02,EUROPE,3,001,0030010163042,8741,11,2,100,100,163
28,8177605,99998475840156675293,14/03/2017,16:34:29,QUATRE SEPTEMBRE,3,001,0030030060400,102,31,3,100,110,ND
29,12275237,99998475840156675293,14/03/2017,16:59:36,COLOMBES,2,002,381087,1350503,2,1,800,854,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471708,1741739,00002570422068427755,14/03/2017,11:19:00,BARBES-ROCHECHOUART,3,001,0030030210700,104,31,3,100,110,ND
1471709,1741827,00002570422068427755,14/03/2017,21:14:06,PERE LACHAISE,3,001,0030030240400,104,31,3,100,110,ND
1471710,10035593,00002055082001887666,14/03/2017,09:36:05,LE KREMLIN-BICETRE,3,001,0030030260600,103,31,3,100,110,ND
1471711,10035681,00002055082001887666,14/03/2017,17:38:27,PONT-NEUF (LA MONNAIE),3,001,0030030011300,201,31,3,100,110,ND
1471712,11727971,00001798538924103426,14/03/2017,08:54:46,POTERNE DES PEUPLIERS,3,001,0030010013030,4939,41,4,100,112,13
1471713,11728059,00001798538924103426,14/03/2017,17:30:54,PORTE DE BRANCION,3,001,0030010013006,18131,41,4,100,112,13
1471714,7771111,00001796207351021427,14/03/2017,12:12:31,ROBESPIERRE,3,001,0030030050200,103,31,3,100,110,ND
1471715,7771199,00001796207351021427,14/03/2017,19:29:46,NATION,3,001,0030030051000,101,31,3,100,110,ND
1471716,67247,00001715107555054797,14/03/2017,13:05:54,LES PLANTES,3,1,0030010062022,1750,11,2,100,100,62
1471717,9082407,00001715107555054797,14/03/2017,21:39:44,GLACIERE - TOLBIAC,3,001,0030010062048,4681,11,2,100,100,62
1471718,11271634,00001656479227785638,14/03/2017,08:51:00,Gare SNCF,124,24,1117,1257,11,2,24,24,7
1471719,7095682,00001656479227785638,14/03/2017,15:03:00,Collège le Parc de Villeroy,124,24,1101,43043,11,2,24,24,7
1471720,7813464,00001510465801441277,14/03/2017,08:29:26,CONDORCET - MAIRIE - RER,3,001,0030010197058,14336,11,2,100,100,197
1471721,7813552,00001510465801441277,14/03/2017,17:17:14,GABRIEL PERI,3,001,0030010197002,2213,11,2,100,100,197
1471722,10997431,00001365566759321417,14/03/2017,06:52:25,SAINT-DENIS-UNIVERSITE,3,1,0030030101100,102,31,3,100,110,ND
1471723,2413207,00001365566759321417,14/03/2017,17:09:53,SAINT-PAUL (LE MARAIS),3,001,0030030121000,101,31,3,100,110,ND
1471724,12035911,00001232695827975166,14/03/2017,08:52:03,BOISSIERE,3,1,0030030171400,102,31,3,100,110,ND
1471725,12035999,00001232695827975166,14/03/2017,17:30:43,CORENTIN-CELTON,3,1,0030030280200,101,31,3,100,110,ND
1471726,10156054,00001192996423384919,14/03/2017,10:05:55,ECOLE VETERINAIRE DE MAISONS-ALFORT,3,001,0030030251400,101,31,3,100,110,ND
1471727,10156142,00001192996423384919,14/03/2017,20:39:24,ETIENNE-MARCEL,3,001,0030030111500,101,31,3,100,110,ND
1471728,7464608,00001144572979536043,14/03/2017,07:28:36,ETAMPES,2,002,545137,1421503,1,1,800,803,ND
1471729,3032048,00001144572979536043,14/03/2017,18:33:16,PETIT-VAUX,2,002,393652,1651401,1,1,800,803,ND
1471730,9533357,00001001433896744337,14/03/2017,09:30:00,République,130,30,54,48032,11,2,30,30,5
1471731,5393045,00001001433896744337,14/03/2017,09:41:00,Gare de Montigny Beauchamp,130,30,163,2767,11,2,30,30,10
1471732,10860373,00000526852634666538,14/03/2017,09:55:48,VILLIERS DE L'ISLE ADAM,3,001,0030010026055,11299,11,2,100,100,26
1471733,6744613,00000526852634666538,14/03/2017,11:15:50,MARAICHERS,3,001,0030010026005,8310,11,2,100,100,26
1471734,12218852,00000465236290425225,14/03/2017,07:50:28,CROIX DE CHAVAUX (JACQUES DUCLOS),3,001,0030030250200,231,31,3,100,110,ND
1471735,3736884,00000465236290425225,14/03/2017,21:03:44,SAINT-PHILIPPE-DU-ROULE,3,001,0030030180500,101,31,3,100,110,ND
1471736,8193031,00000287155699853425,14/03/2017,16:36:40,HOTEL DE VILLE - MAISON DE LA CULTURE,3,001,0030010921007,6406,41,4,100,112,11
1471737,12388167,00000287155699853425,14/03/2017,17:05:46,HOPITAL AVICENNE,3,001,0030010921040,338,41,4,100,112,11

In [73]:
data_1['COD_NATR_VALD'] = data_1['COD_NATR_VALD'].astype('str')
data_1['HEUR_VALD'] = pd.to_timedelta(data_1['HEUR_VALD'])
data_1_sort = data_1.sort_values(['NUMR_CART','HEUR_VALD'], ascending=[False, True])
data_1_sort = data_1_sort.reset_index(drop = True)

In [17]:
test = data_3_sort[data_3_sort['NUMR_CART'] == '35582761024116677984']

In [18]:
test

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
895914,38,35582761024116677984,14/03/2017,07:58:15,FONTENAY-AUX-ROSES,1,802,0030050280402,333,51,1,810,802,ND
895915,8879414,35582761024116677984,14/03/2017,16:38:14,ORSAY-VILLE,1,802,0030050180902,341,51,1,810,802,ND
895916,126,35582761024116677984,14/03/2017,17:17:40,FONTENAY-AUX-ROSES,1,802,0030050280402,243,52,1,810,802,ND

In [28]:
def  output(data, n):
    trip_id = 0
    trips = pd.DataFrame()
    for index in range(int(len(data)/n)):
        a,b = trip_prediction_no_location(data, n, index*n, trip_id)
        trips =  trips.append(a, ignore_index = True)
        trip_id = b + 1
    return trips

In [79]:
def  output_n(data, n):
    transfer_id = 0
    trips = pd.DataFrame([], columns=columns_n)
    range_index = int(len(data)/n)
    for x in range(range_index):
        index = x*n
        i = 0
        trip_id = 0
        start = data.loc[index]     #start would be used in the final trip
        end = data.loc[index+n-1]
        trip_start_time = start['HEUR_VALD']   
        while i+1 < n:
            first = data.loc[index+i]
            second = data.loc[index+i+1]
            trips.loc[transfer_id] = [trip_id, first['NUMR_CART'], first['JOUR_EXPL_VALD'], 
                          first['Lib_Arret'], second['Lib_Arret'], first['HEUR_VALD'], second['HEUR_VALD'], first['COD_TLB_RES'], 
                          first['COD_TLB_ARRT_STTN'],second['COD_TLB_ARRT_STTN'],
                          first['COD_STF_LIGN'], 'd', first['COD_MOD_VALD'], second['COD_MOD_VALD']]
            if second['COD_NATR_VALD'] in sortie:
                trips.loc[transfer_id, 'unkonwn'] = 'no'
                transfer_id = transfer_id + 1 
                i = i + 2
            else:
                trips.loc[transfer_id, 'unkonwn'] = 'd'
                transfer_id = transfer_id + 1
                i = i + 1
                if (second['HEUR_VALD'] - trip_start_time).seconds > T:
                    trip_start_time = second['HEUR_VALD']
                    trip_id = trip_id + 1
        if (i+1) == n:  # which means the last trip is a 'E'
            if (end['HEUR_VALD'] -  trip_start_time).seconds > T:
                trip_id = trip_id + 1
            trips.loc[transfer_id] = [trip_id, end['NUMR_CART'], end['JOUR_EXPL_VALD'], 
                         end['Lib_Arret'], start['Lib_Arret'], end['HEUR_VALD'], '', 
                         end['COD_TLB_RES'], end['COD_TLB_ARRT_STTN'],start['COD_TLB_ARRT_STTN'], 
                         end['COD_STF_LIGN'], 'd', end['COD_MOD_VALD'], start['COD_MOD_VALD']]
            trips.loc[transfer_id, 'unkonwn'] = 'dh'
            if (end['HEUR_VALD'] - start['HEUR_VALD']).seconds < T:
                trips.loc[transfer_id, 'unkonwn'] = 'all'
        transfer_id = transfer_id + 1
    return trips

In [82]:
len(data_3_sort)

1392885

In [99]:
#len(data_2_sort)
select_data = data_3_sort.iloc[:139287]
select_data

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
0,6289284,99999942845366768893,14/03/2017,10:57:31,PYRENEES,3,001,0030030241400,101,31,3,100,110,ND
1,6289196,99999942845366768893,14/03/2017,17:30:51,SAINT-GERMAIN-DES-PRES,3,001,0030030021500,232,31,3,100,110,ND
2,1723316,99999942845366768893,14/03/2017,18:50:29,CHATELET,3,001,0030030010800,401,31,3,100,110,ND
3,7153827,99999577198461515588,14/03/2017,08:00:58,HOTEL DE VILLE DE FONTENAY,3,001,0030010124016,2125,11,2,100,100,124
4,7153915,99999577198461515588,14/03/2017,08:20:46,VAL DE FONTENAY RER,3,001,0030010118015,6803,11,2,100,100,118
5,11376859,99999577198461515588,14/03/2017,19:25:28,VAL DE FONTENAY RER,3,001,0030010124022,9042,11,2,100,100,124
6,354119,99999492695837542235,14/03/2017,08:02:30,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,3,001,0030010151012,611,11,2,100,100,151
7,354031,99999492695837542235,14/03/2017,10:11:44,PLACE DU 19 MARS 1962,3,001,0030010151034,11948,11,2,100,100,151
8,354207,99999492695837542235,14/03/2017,12:29:00,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,3,001,0030010151012,1753,11,2,100,100,151
9,6550859,99998853895565292735,14/03/2017,07:56:20,MAIRIE DE ROMAINVILLE,3,001,0030010105047,983,11,2,100,100,105
10,6550947,99998853895565292735,14/03/2017,08:10:03,MAIRIE DES LILAS,3,001,0030030230300,104,31,3,100,110,ND
11,6551035,99998853895565292735,14/03/2017,17:09:35,PYRENEES,3,001,0030030241400,103,31,3,100,110,ND
12,11137569,99998786964033820793,14/03/2017,08:29:10,RICHELIEU-DROUOT,3,001,0030030110700,401,31,3,100,110,ND
13,2536801,99998786964033820793,14/03/2017,15:53:07,LA MUETTE,3,001,0030030171100,102,31,3,100,110,ND
14,2536889,99998786964033820793,14/03/2017,20:12:29,RUE DU BAC,3,001,0030030021000,103,31,3,100,110,ND
15,12431870,99998614886067744792,14/03/2017,09:03:24,GARE DE LYON,3,001,0030030090800,103,031,3,100,110,ND
16,8265510,99998614886067744792,14/03/2017,18:21:02,LOUIS BLANC,3,001,0030030221000,102,31,3,100,110,ND
17,3943302,99998614886067744792,14/03/2017,19:30:47,PORTE DE LA VILLETTE,3,001,0030030030400,105,31,3,100,110,ND
18,7265193,99997990729919865119,14/03/2017,09:13:04,MARCADET-POISSONNIERS,3,001,0030030200900,102,31,3,100,110,ND
19,7265105,99997990729919865119,14/03/2017,19:43:54,MAIRIE DE CLICHY,3,001,0030030190100,102,31,3,100,110,ND
20,2810545,99997990729919865119,14/03/2017,19:59:14,BROCHANT - CARDINET,3,001,0030010031034,14809,11,2,100,100,31
21,10789855,99997955226236728234,14/03/2017,18:07:30,CERGY-SAINT-CHRISTOPHE,1,801,382499,22331201,1,1,810,801,ND
22,10789679,99997955226236728234,14/03/2017,18:35:00,Gare d'Houilles Carrières sur Seine,119,248,19079,3575,11,2,19,248,19
23,10789767,99997955226236728234,14/03/2017,18:41:19,HOUILLES-CARRIERES-SUR-SEINE,1,801,386409,30320704,2,1,810,801,ND
24,7381774,99997804846299180110,14/03/2017,09:03:11,LES VALLEES,2,002,386300,3320505,1,1,800,854,ND
25,7381862,99997804846299180110,14/03/2017,09:14:38,NANTERRE-VILLE,1,801,0030050170503,208,52,1,810,801,ND
26,7381950,99997804846299180110,14/03/2017,18:50:13,NANTERRE-VILLE,1,801,0030050170503,201,51,1,810,801,ND
27,5467559,99997800772878601333,14/03/2017,13:07:09,GUY MOQUET,3,001,0030030301200,101,31,3,100,110,ND
28,770559,99997800772878601333,14/03/2017,16:37:29,CHATELET,3,001,0030030010800,103,31,3,100,110,ND
29,9660055,99997800772878601333,14/03/2017,18:07:47,JOURDAIN,3,001,0030030231400,103,31,3,100,110,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139257,8155449,89905229935114781222,14/03/2017,08:19:37,REPUBLIQUE,3,001,0030030080700,101,31,3,100,110,ND
139258,3778153,89905229935114781222,14/03/2017,16:37:14,SOLFERINO,3,1,0030030101400,262,31,3,100,110,ND
139259,3778241,89905229935114781222,14/03/2017,19:17:39,CONCORDE,3,1,0030030100200,105,31,3,100,110,ND
139260,7923029,89905209333169718602,14/03/2017,08:35:06,COMMERCE,3,001,0030030170500,103,31,3,100,110,ND
139261,12069853,89905209333169718602,14/03/2017,16:36:02,MAIRIE DU VE - PANTHEON,3,001,0030010084016,16669,11,2,100,100,84
139262,7923117,89905209333169718602,14/03/2017,16:44:44,EGLISE SAINT-SULPICE,3,001,0030010070007,3929,11,2,100,100,70
139263,8158337,89904686598944603272,14/03/2017,09:07:47,CHARLES DE GAULLE ETOILE,3,001,0030030181200,105,31,3,100,110,ND
139264,3827593,89904686598944603272,14/03/2017,18:01:48,CHATILLON-MONTROUGE,3,1,0030030270900,102,31,3,100,110,ND
139265,3827681,89904686598944603272,14/03/2017,19:20:15,CONCORDE,3,001,0030030100200,201,31,3,100,110,ND
139266,8871711,89904473739595752465,14/03/2017,06:51:01,PYRENEES,3,001,0030030241400,102,31,3,100,110,ND
139267,13031159,89904473739595752465,14/03/2017,17:08:12,VILLENNES-SUR-SEINE,2,002,386649,3321101,1,1,800,854,ND
139268,4652111,89904473739595752465,14/03/2017,17:42:03,SAINT-LAZARE,3,001,0030030060800,207,31,3,100,110,ND
139269,6064066,89904280226025433522,14/03/2017,19:37:30,MARCEL SEMBAT-METRO,3,001,0030010123013,675,11,2,100,100,123
139270,6064154,89904280226025433522,14/03/2017,19:43:40,BOULOGNE-JEAN JAURES,3,001,0030030290400,103,31,3,100,110,ND
139271,10232978,89904280226025433522,14/03/2017,21:48:14,CHARLES MICHELS,3,001,0030030161300,101,31,3,100,110,ND
139272,11053988,89904276918737627819,14/03/2017,08:48:14,VIGNERONS,3,001,0030010318056,2564,11,2,100,100,318
139273,6801740,89904276918737627819,14/03/2017,13:04:27,GALLIENI (PARC DE BAGNOLET),3,001,0030030230500,104,31,3,100,110,ND
139274,6801652,89904276918737627819,14/03/2017,17:53:01,PORTE MAILLOT,3,001,0030030300100,107,31,3,100,110,ND
139275,703689,89904257556260426794,14/03/2017,08:05:00,Clos Bertin,130,30,18,38136,11,2,30,30,3
139276,9583065,89904257556260426794,14/03/2017,12:38:54,CLOS MILONS,3,001,0030010261012,10628,11,2,100,100,261
139277,9582977,89904257556260426794,14/03/2017,13:34:00,Clos Bertin,130,195,18,2207,11,2,30,195,19
139278,3182976,89904143084393287936,14/03/2017,11:23:18,ROUGET DE LISLE,3,001,0030010183052,4582,11,2,100,100,183
139279,3183064,89904143084393287936,14/03/2017,18:47:06,LA CIVETTE,3,001,0030010183008,522,11,2,100,100,183
139280,11762096,89904143084393287936,14/03/2017,19:06:36,ROUGET DE LISLE,3,001,0030010183018,14503,11,2,100,100,183
139281,12653567,89903915934346907452,14/03/2017,07:25:00,L'AVENIR,3,1,0030010252022,6724,11,2,100,100,252
139282,8483687,89903915934346907452,14/03/2017,08:09:57,PORTE DE LA CHAPELLE,3,001,0030030200600,101,31,3,100,110,ND
139283,4211727,89903915934346907452,14/03/2017,13:24:59,ALESIA,3,1,0030030150500,104,31,3,100,110,ND
139284,2654872,89903718468383775415,14/03/2017,08:59:22,DENFERT-ROCHEREAU,3,001,0030030151400,104,31,3,100,110,ND
139285,7074584,89903718468383775415,14/03/2017,18:42:40,MAIRIE DE CLICHY,3,001,0030030190100,105,31,3,100,110,ND
139286,2654784,89903718468383775415,14/03/2017,19:46:38,VAVIN,3,001,0030030040700,102,31,3,100,110,ND

In [ ]:
output_file = output_n(select_data, 3)

In [75]:
select_data[select_data['NUMR_CART'] == '99999942845366768893']

,Unnamed: 0,NUMR_CART,JOUR_EXPL_VALD,HEUR_VALD,Lib_Arret,COD_TLB_TRNS,COD_TLB_RES,COD_TLB_ARRT_STTN,NUMR_BORN_VALD_EQPM,COD_NATR_VALD,COD_MOD_VALD,COD_STF_TRNS,COD_STF_RES,COD_STF_LIGN
0,6289284,99999942845366768893,14/03/2017,10:57:31,PYRENEES,3,001,0030030241400,101,31,3,100,110,ND
1,6289196,99999942845366768893,14/03/2017,17:30:51,SAINT-GERMAIN-DES-PRES,3,001,0030030021500,232,31,3,100,110,ND
2,1723316,99999942845366768893,14/03/2017,18:50:29,CHATELET,3,001,0030030010800,401,31,3,100,110,ND

In [94]:
output_file

,trip_id,client_id,date,O,D,Ot,Dt,mode,O_station,D_station,ligne,unkonwn,O_mode,D_mode
0,0,99999942845366768893,14/03/2017,PYRENEES,SAINT-GERMAIN-DES-PRES,10:57:31,0 days 17:30:51,001,0030030241400,0030030021500,ND,d,3,3
1,1,99999942845366768893,14/03/2017,SAINT-GERMAIN-DES-PRES,CHATELET,17:30:51,0 days 18:50:29,001,0030030021500,0030030010800,ND,d,3,3
2,1,99999942845366768893,14/03/2017,CHATELET,PYRENEES,18:50:29,,001,0030030010800,0030030241400,ND,dh,3,3
3,0,99999577198461515588,14/03/2017,HOTEL DE VILLE DE FONTENAY,VAL DE FONTENAY RER,08:00:58,0 days 08:20:46,001,0030010124016,0030010118015,124,d,2,2
4,0,99999577198461515588,14/03/2017,VAL DE FONTENAY RER,VAL DE FONTENAY RER,08:20:46,0 days 19:25:28,001,0030010118015,0030010124022,118,d,2,2
5,1,99999577198461515588,14/03/2017,VAL DE FONTENAY RER,HOTEL DE VILLE DE FONTENAY,19:25:28,,001,0030010124022,0030010124016,124,dh,2,2
6,0,99999492695837542235,14/03/2017,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,PLACE DU 19 MARS 1962,08:02:30,0 days 10:11:44,001,0030010151012,0030010151034,151,d,2,2
7,1,99999492695837542235,14/03/2017,PLACE DU 19 MARS 1962,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,10:11:44,0 days 12:29:00,001,0030010151034,0030010151012,151,d,2,2
8,2,99999492695837542235,14/03/2017,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,ESCADRILLE NORMANDIE-NIEMEN - PAUL VAILLANT-CO...,12:29:00,,001,0030010151012,0030010151012,151,dh,2,2
9,0,99998853895565292735,14/03/2017,MAIRIE DE ROMAINVILLE,MAIRIE DES LILAS,07:56:20,0 days 08:10:03,001,0030010105047,0030030230300,105,d,2,3
10,0,99998853895565292735,14/03/2017,MAIRIE DES LILAS,PYRENEES,08:10:03,0 days 17:09:35,001,0030030230300,0030030241400,ND,d,3,3
11,1,99998853895565292735,14/03/2017,PYRENEES,MAIRIE DE ROMAINVILLE,17:09:35,,001,0030030241400,0030010105047,ND,dh,3,2
12,0,99998786964033820793,14/03/2017,RICHELIEU-DROUOT,LA MUETTE,08:29:10,0 days 15:53:07,001,0030030110700,0030030171100,ND,d,3,3
13,1,99998786964033820793,14/03/2017,LA MUETTE,RUE DU BAC,15:53:07,0 days 20:12:29,001,0030030171100,0030030021000,ND,d,3,3
14,2,99998786964033820793,14/03/2017,RUE DU BAC,RICHELIEU-DROUOT,20:12:29,,001,0030030021000,0030030110700,ND,dh,3,3
15,0,99998614886067744792,14/03/2017,GARE DE LYON,LOUIS BLANC,09:03:24,0 days 18:21:02,001,0030030090800,0030030221000,ND,d,3,3
16,1,99998614886067744792,14/03/2017,LOUIS BLANC,PORTE DE LA VILLETTE,18:21:02,0 days 19:30:47,001,0030030221000,0030030030400,ND,d,3,3
17,1,99998614886067744792,14/03/2017,PORTE DE LA VILLETTE,GARE DE LYON,19:30:47,,001,0030030030400,0030030090800,ND,dh,3,3
18,0,99997990729919865119,14/03/2017,MARCADET-POISSONNIERS,MAIRIE DE CLICHY,09:13:04,0 days 19:43:54,001,0030030200900,0030030190100,ND,d,3,3
19,1,99997990729919865119,14/03/2017,MAIRIE DE CLICHY,BROCHANT - CARDINET,19:43:54,0 days 19:59:14,001,0030030190100,0030010031034,ND,d,3,2
20,1,99997990729919865119,14/03/2017,BROCHANT - CARDINET,MARCADET-POISSONNIERS,19:59:14,,001,0030010031034,0030030200900,31,dh,2,3
21,0,99997955226236728234,14/03/2017,CERGY-SAINT-CHRISTOPHE,Gare d'Houilles Carrières sur Seine,18:07:30,0 days 18:35:00,801,382499,19079,ND,d,1,2
22,0,99997955226236728234,14/03/2017,Gare d'Houilles Carrières sur Seine,HOUILLES-CARRIERES-SUR-SEINE,18:35:00,0 days 18:41:19,248,19079,386409,19,no,2,1
24,0,99997804846299180110,14/03/2017,LES VALLEES,NANTERRE-VILLE,09:03:11,0 days 09:14:38,002,386300,0030050170503,ND,no,1,1
25,1,99997804846299180110,14/03/2017,NANTERRE-VILLE,LES VALLEES,18:50:13,,801,0030050170503,386300,ND,dh,1,1
26,0,99997800772878601333,14/03/2017,GUY MOQUET,CHATELET,13:07:09,0 days 16:37:29,001,0030030301200,0030030010800,ND,d,3,3
27,1,99997800772878601333,14/03/2017,CHATELET,JOURDAIN,16:37:29,0 days 18:07:47,001,0030030010800,0030030231400,ND,d,3,3
28,1,99997800772878601333,14/03/2017,JOURDAIN,GUY MOQUET,18:07:47,,001,0030030231400,0030030301200,ND,dh,3,3
29,0,99997570798660882124,14/03/2017,Résidence La Forêt,Gare Rive Droite,09:46:00,0 days 10:47:00,56,226,580,5,d,2,2
30,0,99997570798660882124,14/03/2017,Gare Rive Droite,Pershing,10:47:00,0 days 10:48:00,56,580,165,5,d,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13234,0,98973325740861255168,14/03/2017,ALEXANDRE DUMAS,Inconnu,07:35:28,0 days 12:58:09,001,0030030051300,ND,ND,d,3,3
13235,1,98973325740861255168,14/03/2017,Inconnu,ANVERS,12:58:09,0 days 18:24:09,ND,ND,0030030310400,ND,d,3,3
13236,2,98973325740861255168,14/03/2017,ANVERS,ALEXANDRE DUMAS,18:24:09,,001,0030030310400,0030030051300,ND,dh,3,3
13237,0,98973103943593562827,14/03/2017,PORTE DE VERSAILLES,JACQUES-HENRI LARTIGUE,08:30:42,0 days 18:11:38,001,0030010019029,0030010019024,12,d,4,4
13238,1,98973103943593562827,14/03/2017,JACQUES-HENRI LARTIGUE,PORTE DE VERSAILLES,18:11:38,0 days 18:22:49,001,0030010019024,0030030160600,12,d,4,3
13239,1,98973103943593562827,14/03/2017,PORTE DE VERSAILLES,PORTE DE VERSAILLES,18:22:49,,001,0030030160600,0030010019029,ND,dh,3,4
13240,0,98972927682504835596,14/03/2017,FORT D'AUBERVILLIERS,BREGUET-SABIN,08:58:42,0 days 18:27:43,001,0030030030600,0030030121400,ND,d,3,3
13241,1,98972927682504835596,14/03/2017,BREGUET-SABIN,FORT D'AUBERVILLIERS - DANIELLE CASANOVA,18:27:43,0 days 18:56:42,001,0030030121400,0030010173037,ND,d,3,2
13242,1,98972927682504835596,14/03/2017,FORT D'AUBERVILLIERS - DANIELLE CASANOVA,FORT D'AUBERVILLIERS,18:56:42,,001,0030010173037,0030030030600,173,dh,2,3
13243,0,98972693826842201205,14/03/2017,BIBLIOTHEQUE FRANCOIS MITTERRAND,LA COURNEUVE-AUBERVILLIERS,12:09:20,0 days 19:10:27,002,328328,271304,ND,d,1,1
13244,1,98972693826842201205,14/03/2017,LA COURNEUVE-AUBERVILLIERS,BIBLIOTHEQUE FRANCOIS MITTERRAND,19:10:27,0 days 19:48:52,802,271304,328328,ND,no,1,1
13246,0,98972639689274221810,14/03/2017,LA COURNEUVE 8 MAI 1945,SAINT-GERMAIN-DES-PRES,11:18:02,0 days 21:57:31,001,0030030030700,0030030021500,ND,d,3,3
13247,1,98972639689274221810,14/03/2017,SAINT-GERMAIN-DES-PRES,FORT D'AUBERVILLIERS - METRO,21:57:31,0 days 22:30:04,001,0030030021500,0030010234001,ND,d,3,2
13248,1,98972639689274221810,14/03/2017,FORT D'AUBERVILLIERS - METRO,LA COURNEUVE 8 MAI 1945,22:30:04,,001,0030010234001,0030030030700,234,dh,2,3
13249,0,98972612161280585636,14/03/2017,RUEIL MALMAI,RUEIL-MALMAISON,08:13:00,0 days 12:46:49,100,1457,0030050170601,467,d,2,1
13250,1,98972612161280585636,14/03/2017,RUEIL-MALMAISON,LA GARENNE-COLOMBES,12:46:49,0 days 18:52:12,801,0030050170601,386003,ND,no,1,1
13252,0,98972557352478156776,14/03/2017,JUVISY,ARCUEIL-CACHAN,08:23:27,0 days 20:06:25,002,545244,0030050180203,ND,d,1,1
13253,1,98972557352478156776,14/03/2017,ARCUEIL-CACHAN,JUVISY,20:06:25,0 days 20:47:03,802,0030050180203,545244,ND,no,1,1
13255,0,98972460837975510297,14/03/2017,VICTORIEN SARDOU,LES GODARDES,09:16:08,0 days 10:46:34,001,0030010141052,0030010244016,141,d,2,2
13256,0,98972460837975510297,14/03/2017,LES GODARDES,RUEIL-MALMAISON RER,10:46:34,0 days 18:16:00,001,0030010244016,0030010241039,244,d,2,2
13257,1,98972460837975510297,14/03/2017,RUEIL-MALMAISON RER,VICTORIEN SARDOU,18:16:00,,001,0030010241039,0030010141052,241,dh,2,2
13258,0,98972289238280193976,14/03/2017,VAILLANT COUTURIER-LENINE,ECOLE VETERINAIRE DE MAISONS-ALFORT,10:20:30,0 days 10:33:01,1,0030010125022,0030030251400,125,d,2,3
13259,0,98972289238280193976,14/03/2017,ECOLE VETERINAIRE DE MAISONS-ALFORT,CRETEIL-L'ECHAT (HOPITAL MONDOR),10:33:01,0 days 17:36:31,001,0030030251400,0030030250500,ND,d,3,3
13260,1,98972289238280193976,14/03/2017,CRETEIL-L'ECHAT (HOPITAL MONDOR),VAILLANT COUTURIER-LENINE,17:36:31,,001,0030030250500,0030010125022,ND,dh,3,2
13261,0,98971705222409948148,14/03/2017,ESPLANADE DE LA DEFENSE,MONCEAU,08:46:29,0 days 18:38:10,001,0030030291000,0030030060200,ND,d,3,3
13262,1,98971705222409948148,14/03/2017,MONCEAU,LA DEFENSE RER,18:38:10,0 days 19:07:42,001,0030030060200,0030010360001,ND,d,3,2
13263,1,98971705222409948148,14/03/2017,LA DEFENSE RER,ESPLANADE DE LA DEFENSE,19:07:42,,001,0030010360001,0030030291000,360,dh,2,3
13264,0,98971290146185221897,14/03/2017,MAIRIE DE CLICHY,LAMARCK-CAULAINCOURT,08:37:09,0 days 12:29:31,001,0030030190100,0030030201200,ND,d,3,3
13265,1,98971290146185221897,14/03/2017,LAMARCK-CAULAINCOURT,MARCADET-POISSONNIERS,12:29:31,0 days 15:49:37,001,0030030201200,0030030200900,ND,d,3,3
13266,2,98971290146185221897,14/03/2017,MARCADET-POISSONNIERS,MAIRIE DE CLICHY,15:49:37,,001,0030030200900,0030030190100,ND,dh,3,3

In [77]:
output_path = 'E:/Study/data/2_0.csv'

In [78]:
output_file.to_csv(output_path, header=True,sep="\t", encoding='latin-1')

In [23]:
select_data.iloc[87]

Unnamed: 0                          6365981
NUMR_CART              99993438346376835101
JOUR_EXPL_VALD                   14/03/2017
HEUR_VALD                   0 days 19:51:32
Lib_Arret                      CRETEIL POMP
COD_TLB_TRNS                              2
COD_TLB_RES                             002
COD_TLB_ARRT_STTN             608802
NUMR_BORN_VALD_EQPM                 5400603
COD_NATR_VALD                             2
COD_MOD_VALD                              1
COD_STF_TRNS                            800
COD_STF_RES                             804
COD_STF_LIGN                            ND
Name: 87, dtype: object

In [24]:
z = pd.DataFrame()
z = z.append(x)
z = z.append(x, ignore_index=True)
z

NameError: name 'x' is not defined